// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aftersales_service.proto

package proto // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EAfterSalesType int32

const (
	// 默认
	EAfterSalesType_TypeUnset EAfterSalesType = 0
	// 退款申请(部分退款)
	EAfterSalesType_TypeRefund EAfterSalesType = 1
	// 退货
	EAfterSalesType_TypeReturn EAfterSalesType = 2
	// 换货
	EAfterSalesType_TypeExchange EAfterSalesType = 3
	// 服务/维修
	EAfterSalesType_TypeService EAfterSalesType = 4
)

var EAfterSalesType_name = map[int32]string{
	0: "TypeUnset",
	1: "TypeRefund",
	2: "TypeReturn",
	3: "TypeExchange",
	4: "TypeService",
}
var EAfterSalesType_value = map[string]int32{
	"TypeUnset":    0,
	"TypeRefund":   1,
	"TypeReturn":   2,
	"TypeExchange": 3,
	"TypeService":  4,
}

func (x EAfterSalesType) String() string {
	return proto.EnumName(EAfterSalesType_name, int32(x))
}
func (EAfterSalesType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{0}
}

// 原实际销售的订单编号
type OriginOrderIdRequest struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginOrderIdRequest) Reset()         { *m = OriginOrderIdRequest{} }
func (m *OriginOrderIdRequest) String() string { return proto.CompactTextString(m) }
func (*OriginOrderIdRequest) ProtoMessage()    {}
func (*OriginOrderIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{0}
}
func (m *OriginOrderIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginOrderIdRequest.Unmarshal(m, b)
}
func (m *OriginOrderIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginOrderIdRequest.Marshal(b, m, deterministic)
}
func (dst *OriginOrderIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginOrderIdRequest.Merge(dst, src)
}
func (m *OriginOrderIdRequest) XXX_Size() int {
	return xxx_messageInfo_OriginOrderIdRequest.Size(m)
}
func (m *OriginOrderIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginOrderIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginOrderIdRequest proto.InternalMessageInfo

func (m *OriginOrderIdRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type SubmitAfterSalesOrderRequest struct {
	OrderId              int64           `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	AfterSalesType       EAfterSalesType `protobuf:"varint,2,opt,name=AfterSalesType,proto3,enum=EAfterSalesType" json:"AfterSalesType,omitempty"`
	ItemSnapshotId       int64           `protobuf:"varint,3,opt,name=ItemSnapshotId,proto3" json:"ItemSnapshotId,omitempty"`
	Quantity             int64           `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Reason               string          `protobuf:"bytes,5,opt,name=Reason,proto3" json:"Reason,omitempty"`
	ImageUrl             string          `protobuf:"bytes,6,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SubmitAfterSalesOrderRequest) Reset()         { *m = SubmitAfterSalesOrderRequest{} }
func (m *SubmitAfterSalesOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitAfterSalesOrderRequest) ProtoMessage()    {}
func (*SubmitAfterSalesOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{1}
}
func (m *SubmitAfterSalesOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitAfterSalesOrderRequest.Unmarshal(m, b)
}
func (m *SubmitAfterSalesOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitAfterSalesOrderRequest.Marshal(b, m, deterministic)
}
func (dst *SubmitAfterSalesOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAfterSalesOrderRequest.Merge(dst, src)
}
func (m *SubmitAfterSalesOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitAfterSalesOrderRequest.Size(m)
}
func (m *SubmitAfterSalesOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAfterSalesOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAfterSalesOrderRequest proto.InternalMessageInfo

func (m *SubmitAfterSalesOrderRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *SubmitAfterSalesOrderRequest) GetAfterSalesType() EAfterSalesType {
	if m != nil {
		return m.AfterSalesType
	}
	return EAfterSalesType_TypeUnset
}

func (m *SubmitAfterSalesOrderRequest) GetItemSnapshotId() int64 {
	if m != nil {
		return m.ItemSnapshotId
	}
	return 0
}

func (m *SubmitAfterSalesOrderRequest) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SubmitAfterSalesOrderRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *SubmitAfterSalesOrderRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type SubmitAfterSalesOrderResponse struct {
	ErrCode              int64    `protobuf:"varint,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	AfterSalesOrderId    int64    `protobuf:"varint,3,opt,name=AfterSalesOrderId,proto3" json:"AfterSalesOrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitAfterSalesOrderResponse) Reset()         { *m = SubmitAfterSalesOrderResponse{} }
func (m *SubmitAfterSalesOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitAfterSalesOrderResponse) ProtoMessage()    {}
func (*SubmitAfterSalesOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{2}
}
func (m *SubmitAfterSalesOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitAfterSalesOrderResponse.Unmarshal(m, b)
}
func (m *SubmitAfterSalesOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitAfterSalesOrderResponse.Marshal(b, m, deterministic)
}
func (dst *SubmitAfterSalesOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAfterSalesOrderResponse.Merge(dst, src)
}
func (m *SubmitAfterSalesOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitAfterSalesOrderResponse.Size(m)
}
func (m *SubmitAfterSalesOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAfterSalesOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAfterSalesOrderResponse proto.InternalMessageInfo

func (m *SubmitAfterSalesOrderResponse) GetErrCode() int64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *SubmitAfterSalesOrderResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *SubmitAfterSalesOrderResponse) GetAfterSalesOrderId() int64 {
	if m != nil {
		return m.AfterSalesOrderId
	}
	return 0
}

type AfterSalesOrderListResponse struct {
	Value                []*SAfterSalesOrder `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AfterSalesOrderListResponse) Reset()         { *m = AfterSalesOrderListResponse{} }
func (m *AfterSalesOrderListResponse) String() string { return proto.CompactTextString(m) }
func (*AfterSalesOrderListResponse) ProtoMessage()    {}
func (*AfterSalesOrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{3}
}
func (m *AfterSalesOrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AfterSalesOrderListResponse.Unmarshal(m, b)
}
func (m *AfterSalesOrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AfterSalesOrderListResponse.Marshal(b, m, deterministic)
}
func (dst *AfterSalesOrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AfterSalesOrderListResponse.Merge(dst, src)
}
func (m *AfterSalesOrderListResponse) XXX_Size() int {
	return xxx_messageInfo_AfterSalesOrderListResponse.Size(m)
}
func (m *AfterSalesOrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AfterSalesOrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AfterSalesOrderListResponse proto.InternalMessageInfo

func (m *AfterSalesOrderListResponse) GetValue() []*SAfterSalesOrder {
	if m != nil {
		return m.Value
	}
	return nil
}

type PagingBuyerOrdersRequest struct {
	BuyerId              int64          `protobuf:"varint,1,opt,name=BuyerId,proto3" json:"BuyerId,omitempty"`
	Params               *SPagingParams `protobuf:"bytes,2,opt,name=Params,proto3" json:"Params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PagingBuyerOrdersRequest) Reset()         { *m = PagingBuyerOrdersRequest{} }
func (m *PagingBuyerOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*PagingBuyerOrdersRequest) ProtoMessage()    {}
func (*PagingBuyerOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{4}
}
func (m *PagingBuyerOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingBuyerOrdersRequest.Unmarshal(m, b)
}
func (m *PagingBuyerOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingBuyerOrdersRequest.Marshal(b, m, deterministic)
}
func (dst *PagingBuyerOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingBuyerOrdersRequest.Merge(dst, src)
}
func (m *PagingBuyerOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_PagingBuyerOrdersRequest.Size(m)
}
func (m *PagingBuyerOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingBuyerOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PagingBuyerOrdersRequest proto.InternalMessageInfo

func (m *PagingBuyerOrdersRequest) GetBuyerId() int64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

func (m *PagingBuyerOrdersRequest) GetParams() *SPagingParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type PagingSellerOrdersRequest struct {
	SellerId             int64          `protobuf:"varint,1,opt,name=SellerId,proto3" json:"SellerId,omitempty"`
	Params               *SPagingParams `protobuf:"bytes,2,opt,name=Params,proto3" json:"Params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PagingSellerOrdersRequest) Reset()         { *m = PagingSellerOrdersRequest{} }
func (m *PagingSellerOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*PagingSellerOrdersRequest) ProtoMessage()    {}
func (*PagingSellerOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{5}
}
func (m *PagingSellerOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingSellerOrdersRequest.Unmarshal(m, b)
}
func (m *PagingSellerOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingSellerOrdersRequest.Marshal(b, m, deterministic)
}
func (dst *PagingSellerOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingSellerOrdersRequest.Merge(dst, src)
}
func (m *PagingSellerOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_PagingSellerOrdersRequest.Size(m)
}
func (m *PagingSellerOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingSellerOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PagingSellerOrdersRequest proto.InternalMessageInfo

func (m *PagingSellerOrdersRequest) GetSellerId() int64 {
	if m != nil {
		return m.SellerId
	}
	return 0
}

func (m *PagingSellerOrdersRequest) GetParams() *SPagingParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type PagingBuyerAfterSalesOrderListResponse struct {
	Total                int64                          `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Data                 []*SPagingBuyerAfterSalesOrder `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *PagingBuyerAfterSalesOrderListResponse) Reset() {
	*m = PagingBuyerAfterSalesOrderListResponse{}
}
func (m *PagingBuyerAfterSalesOrderListResponse) String() string { return proto.CompactTextString(m) }
func (*PagingBuyerAfterSalesOrderListResponse) ProtoMessage()    {}
func (*PagingBuyerAfterSalesOrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{6}
}
func (m *PagingBuyerAfterSalesOrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingBuyerAfterSalesOrderListResponse.Unmarshal(m, b)
}
func (m *PagingBuyerAfterSalesOrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingBuyerAfterSalesOrderListResponse.Marshal(b, m, deterministic)
}
func (dst *PagingBuyerAfterSalesOrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingBuyerAfterSalesOrderListResponse.Merge(dst, src)
}
func (m *PagingBuyerAfterSalesOrderListResponse) XXX_Size() int {
	return xxx_messageInfo_PagingBuyerAfterSalesOrderListResponse.Size(m)
}
func (m *PagingBuyerAfterSalesOrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingBuyerAfterSalesOrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PagingBuyerAfterSalesOrderListResponse proto.InternalMessageInfo

func (m *PagingBuyerAfterSalesOrderListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PagingBuyerAfterSalesOrderListResponse) GetData() []*SPagingBuyerAfterSalesOrder {
	if m != nil {
		return m.Data
	}
	return nil
}

type PagingSellerAfterSalesOrderListResponse struct {
	Total                int64                           `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Data                 []*SPagingSellerAfterSalesOrder `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *PagingSellerAfterSalesOrderListResponse) Reset() {
	*m = PagingSellerAfterSalesOrderListResponse{}
}
func (m *PagingSellerAfterSalesOrderListResponse) String() string { return proto.CompactTextString(m) }
func (*PagingSellerAfterSalesOrderListResponse) ProtoMessage()    {}
func (*PagingSellerAfterSalesOrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{7}
}
func (m *PagingSellerAfterSalesOrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingSellerAfterSalesOrderListResponse.Unmarshal(m, b)
}
func (m *PagingSellerAfterSalesOrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingSellerAfterSalesOrderListResponse.Marshal(b, m, deterministic)
}
func (dst *PagingSellerAfterSalesOrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingSellerAfterSalesOrderListResponse.Merge(dst, src)
}
func (m *PagingSellerAfterSalesOrderListResponse) XXX_Size() int {
	return xxx_messageInfo_PagingSellerAfterSalesOrderListResponse.Size(m)
}
func (m *PagingSellerAfterSalesOrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingSellerAfterSalesOrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PagingSellerAfterSalesOrderListResponse proto.InternalMessageInfo

func (m *PagingSellerAfterSalesOrderListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PagingSellerAfterSalesOrderListResponse) GetData() []*SPagingSellerAfterSalesOrder {
	if m != nil {
		return m.Data
	}
	return nil
}

// 售后单
type SAfterSalesOrder struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// 订单编号
	RelateOrderId int64 `protobuf:"varint,2,opt,name=RelateOrderId,proto3" json:"RelateOrderId,omitempty"`
	// 运营商编号
	VendorId int64 `protobuf:"varint,3,opt,name=VendorId,proto3" json:"VendorId,omitempty"`
	// 购买者编号
	BuyerId int64 `protobuf:"varint,4,opt,name=BuyerId,proto3" json:"BuyerId,omitempty"`
	// 类型，退货、换货、维修
	AfterSalesType int32 `protobuf:"varint,5,opt,name=AfterSalesType,proto3" json:"AfterSalesType,omitempty"`
	// 退货的商品项编号
	SnapshotId int64 `protobuf:"varint,6,opt,name=SnapshotId,proto3" json:"SnapshotId,omitempty"`
	// 商品数量
	Quantity int32 `protobuf:"varint,7,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	// 售后原因
	Reason string `protobuf:"bytes,8,opt,name=Reason,proto3" json:"Reason,omitempty"`
	// 商品售后图片凭证
	ImageUrl string `protobuf:"bytes,9,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	// 联系人
	PersonName string `protobuf:"bytes,10,opt,name=PersonName,proto3" json:"PersonName,omitempty"`
	// 联系电话
	PersonPhone string `protobuf:"bytes,11,opt,name=PersonPhone,proto3" json:"PersonPhone,omitempty"`
	// 退货的快递服务商编号
	ReturnSpName string `protobuf:"bytes,12,opt,name=ReturnSpName,proto3" json:"ReturnSpName,omitempty"`
	// 退货的快递单号
	ReturnSpOrder string `protobuf:"bytes,13,opt,name=ReturnSpOrder,proto3" json:"ReturnSpOrder,omitempty"`
	// 退货凭证
	ReturnSpImage string `protobuf:"bytes,14,opt,name=ReturnSpImage,proto3" json:"ReturnSpImage,omitempty"`
	// 备注(系统)
	Remark string `protobuf:"bytes,15,opt,name=Remark,proto3" json:"Remark,omitempty"`
	// 运营商备注
	VendorRemark string `protobuf:"bytes,16,opt,name=VendorRemark,proto3" json:"VendorRemark,omitempty"`
	// 售后单状态
	State int32 `protobuf:"varint,17,opt,name=State,proto3" json:"State,omitempty"`
	// 提交时间
	CreateTime int64 `protobuf:"varint,18,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	// 更新时间
	UpdateTime int64 `protobuf:"varint,19,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	// 订单状态
	StateText            string   `protobuf:"bytes,20,opt,name=StateText,proto3" json:"StateText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SAfterSalesOrder) Reset()         { *m = SAfterSalesOrder{} }
func (m *SAfterSalesOrder) String() string { return proto.CompactTextString(m) }
func (*SAfterSalesOrder) ProtoMessage()    {}
func (*SAfterSalesOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{8}
}
func (m *SAfterSalesOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SAfterSalesOrder.Unmarshal(m, b)
}
func (m *SAfterSalesOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SAfterSalesOrder.Marshal(b, m, deterministic)
}
func (dst *SAfterSalesOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SAfterSalesOrder.Merge(dst, src)
}
func (m *SAfterSalesOrder) XXX_Size() int {
	return xxx_messageInfo_SAfterSalesOrder.Size(m)
}
func (m *SAfterSalesOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SAfterSalesOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SAfterSalesOrder proto.InternalMessageInfo

func (m *SAfterSalesOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SAfterSalesOrder) GetRelateOrderId() int64 {
	if m != nil {
		return m.RelateOrderId
	}
	return 0
}

func (m *SAfterSalesOrder) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *SAfterSalesOrder) GetBuyerId() int64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

func (m *SAfterSalesOrder) GetAfterSalesType() int32 {
	if m != nil {
		return m.AfterSalesType
	}
	return 0
}

func (m *SAfterSalesOrder) GetSnapshotId() int64 {
	if m != nil {
		return m.SnapshotId
	}
	return 0
}

func (m *SAfterSalesOrder) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SAfterSalesOrder) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *SAfterSalesOrder) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *SAfterSalesOrder) GetPersonName() string {
	if m != nil {
		return m.PersonName
	}
	return ""
}

func (m *SAfterSalesOrder) GetPersonPhone() string {
	if m != nil {
		return m.PersonPhone
	}
	return ""
}

func (m *SAfterSalesOrder) GetReturnSpName() string {
	if m != nil {
		return m.ReturnSpName
	}
	return ""
}

func (m *SAfterSalesOrder) GetReturnSpOrder() string {
	if m != nil {
		return m.ReturnSpOrder
	}
	return ""
}

func (m *SAfterSalesOrder) GetReturnSpImage() string {
	if m != nil {
		return m.ReturnSpImage
	}
	return ""
}

func (m *SAfterSalesOrder) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *SAfterSalesOrder) GetVendorRemark() string {
	if m != nil {
		return m.VendorRemark
	}
	return ""
}

func (m *SAfterSalesOrder) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *SAfterSalesOrder) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SAfterSalesOrder) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SAfterSalesOrder) GetStateText() string {
	if m != nil {
		return m.StateText
	}
	return ""
}

type SPagingBuyerAfterSalesOrder struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// 订单编号
	OrderNo string `protobuf:"bytes,2,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	// 运营商编号
	VendorId int64 `protobuf:"varint,3,opt,name=VendorId,proto3" json:"VendorId,omitempty"`
	// 运营商名称
	SellerName string `protobuf:"bytes,4,opt,name=SellerName,proto3" json:"SellerName,omitempty"`
	// 类型，退货、换货、维修
	AfterSalesType int32 `protobuf:"varint,5,opt,name=AfterSalesType,proto3" json:"AfterSalesType,omitempty"`
	// 退货的商品项编号
	SnapshotId int64 `protobuf:"varint,6,opt,name=SnapshotId,proto3" json:"SnapshotId,omitempty"`
	// 商品数量
	Quantity  int32  `protobuf:"varint,7,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	SkuId     int64  `protobuf:"varint,8,opt,name=SkuId,proto3" json:"SkuId,omitempty"`
	ItemTitle string `protobuf:"bytes,9,opt,name=ItemTitle,proto3" json:"ItemTitle,omitempty"`
	ItemImage string `protobuf:"bytes,10,opt,name=ItemImage,proto3" json:"ItemImage,omitempty"`
	// 售后单状态
	State int32 `protobuf:"varint,11,opt,name=State,proto3" json:"State,omitempty"`
	// 提交时间
	CreateTime int64 `protobuf:"varint,12,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	// 更新时间
	UpdateTime int64 `protobuf:"varint,13,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	// 订单状态
	StateText            string   `protobuf:"bytes,14,opt,name=StateText,proto3" json:"StateText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SPagingBuyerAfterSalesOrder) Reset()         { *m = SPagingBuyerAfterSalesOrder{} }
func (m *SPagingBuyerAfterSalesOrder) String() string { return proto.CompactTextString(m) }
func (*SPagingBuyerAfterSalesOrder) ProtoMessage()    {}
func (*SPagingBuyerAfterSalesOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{9}
}
func (m *SPagingBuyerAfterSalesOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPagingBuyerAfterSalesOrder.Unmarshal(m, b)
}
func (m *SPagingBuyerAfterSalesOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPagingBuyerAfterSalesOrder.Marshal(b, m, deterministic)
}
func (dst *SPagingBuyerAfterSalesOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPagingBuyerAfterSalesOrder.Merge(dst, src)
}
func (m *SPagingBuyerAfterSalesOrder) XXX_Size() int {
	return xxx_messageInfo_SPagingBuyerAfterSalesOrder.Size(m)
}
func (m *SPagingBuyerAfterSalesOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SPagingBuyerAfterSalesOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SPagingBuyerAfterSalesOrder proto.InternalMessageInfo

func (m *SPagingBuyerAfterSalesOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *SPagingBuyerAfterSalesOrder) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetSellerName() string {
	if m != nil {
		return m.SellerName
	}
	return ""
}

func (m *SPagingBuyerAfterSalesOrder) GetAfterSalesType() int32 {
	if m != nil {
		return m.AfterSalesType
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetSnapshotId() int64 {
	if m != nil {
		return m.SnapshotId
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetItemTitle() string {
	if m != nil {
		return m.ItemTitle
	}
	return ""
}

func (m *SPagingBuyerAfterSalesOrder) GetItemImage() string {
	if m != nil {
		return m.ItemImage
	}
	return ""
}

func (m *SPagingBuyerAfterSalesOrder) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SPagingBuyerAfterSalesOrder) GetStateText() string {
	if m != nil {
		return m.StateText
	}
	return ""
}

// 分页商户售后单
type SPagingSellerAfterSalesOrder struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// 订单编号
	OrderNo string `protobuf:"bytes,2,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	// 会员编号
	BuyerId int64 `protobuf:"varint,3,opt,name=BuyerId,proto3" json:"BuyerId,omitempty"`
	// 会员名称
	BuyerName string `protobuf:"bytes,4,opt,name=BuyerName,proto3" json:"BuyerName,omitempty"`
	// 类型，退货、换货、维修
	AfterSalesType int32 `protobuf:"varint,5,opt,name=AfterSalesType,proto3" json:"AfterSalesType,omitempty"`
	// 退货的商品项编号
	SnapshotId int64 `protobuf:"varint,6,opt,name=SnapshotId,proto3" json:"SnapshotId,omitempty"`
	// 商品数量
	Quantity  int32  `protobuf:"varint,7,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	SkuId     int64  `protobuf:"varint,8,opt,name=SkuId,proto3" json:"SkuId,omitempty"`
	ItemTitle string `protobuf:"bytes,9,opt,name=ItemTitle,proto3" json:"ItemTitle,omitempty"`
	ItemImage string `protobuf:"bytes,10,opt,name=ItemImage,proto3" json:"ItemImage,omitempty"`
	// 售后单状态
	State int32 `protobuf:"varint,11,opt,name=State,proto3" json:"State,omitempty"`
	// 提交时间
	CreateTime int64 `protobuf:"varint,12,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	// 更新时间
	UpdateTime int64 `protobuf:"varint,13,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	// 订单状态
	StateText            string   `protobuf:"bytes,14,opt,name=StateText,proto3" json:"StateText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SPagingSellerAfterSalesOrder) Reset()         { *m = SPagingSellerAfterSalesOrder{} }
func (m *SPagingSellerAfterSalesOrder) String() string { return proto.CompactTextString(m) }
func (*SPagingSellerAfterSalesOrder) ProtoMessage()    {}
func (*SPagingSellerAfterSalesOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{10}
}
func (m *SPagingSellerAfterSalesOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPagingSellerAfterSalesOrder.Unmarshal(m, b)
}
func (m *SPagingSellerAfterSalesOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPagingSellerAfterSalesOrder.Marshal(b, m, deterministic)
}
func (dst *SPagingSellerAfterSalesOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPagingSellerAfterSalesOrder.Merge(dst, src)
}
func (m *SPagingSellerAfterSalesOrder) XXX_Size() int {
	return xxx_messageInfo_SPagingSellerAfterSalesOrder.Size(m)
}
func (m *SPagingSellerAfterSalesOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SPagingSellerAfterSalesOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SPagingSellerAfterSalesOrder proto.InternalMessageInfo

func (m *SPagingSellerAfterSalesOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *SPagingSellerAfterSalesOrder) GetBuyerId() int64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetBuyerName() string {
	if m != nil {
		return m.BuyerName
	}
	return ""
}

func (m *SPagingSellerAfterSalesOrder) GetAfterSalesType() int32 {
	if m != nil {
		return m.AfterSalesType
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetSnapshotId() int64 {
	if m != nil {
		return m.SnapshotId
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetItemTitle() string {
	if m != nil {
		return m.ItemTitle
	}
	return ""
}

func (m *SPagingSellerAfterSalesOrder) GetItemImage() string {
	if m != nil {
		return m.ItemImage
	}
	return ""
}

func (m *SPagingSellerAfterSalesOrder) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SPagingSellerAfterSalesOrder) GetStateText() string {
	if m != nil {
		return m.StateText
	}
	return ""
}

type ExchangeShipmentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SpName               string   `protobuf:"bytes,2,opt,name=SpName,proto3" json:"SpName,omitempty"`
	SpOrder              string   `protobuf:"bytes,3,opt,name=SpOrder,proto3" json:"SpOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeShipmentRequest) Reset()         { *m = ExchangeShipmentRequest{} }
func (m *ExchangeShipmentRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeShipmentRequest) ProtoMessage()    {}
func (*ExchangeShipmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aftersales_service_5dce44e64309fdd8, []int{11}
}
func (m *ExchangeShipmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeShipmentRequest.Unmarshal(m, b)
}
func (m *ExchangeShipmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeShipmentRequest.Marshal(b, m, deterministic)
}
func (dst *ExchangeShipmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeShipmentRequest.Merge(dst, src)
}
func (m *ExchangeShipmentRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeShipmentRequest.Size(m)
}
func (m *ExchangeShipmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeShipmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeShipmentRequest proto.InternalMessageInfo

func (m *ExchangeShipmentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExchangeShipmentRequest) GetSpName() string {
	if m != nil {
		return m.SpName
	}
	return ""
}

func (m *ExchangeShipmentRequest) GetSpOrder() string {
	if m != nil {
		return m.SpOrder
	}
	return ""
}

func init() {
	proto.RegisterType((*OriginOrderIdRequest)(nil), "OriginOrderIdRequest")
	proto.RegisterType((*SubmitAfterSalesOrderRequest)(nil), "SubmitAfterSalesOrderRequest")
	proto.RegisterType((*SubmitAfterSalesOrderResponse)(nil), "SubmitAfterSalesOrderResponse")
	proto.RegisterType((*AfterSalesOrderListResponse)(nil), "AfterSalesOrderListResponse")
	proto.RegisterType((*PagingBuyerOrdersRequest)(nil), "PagingBuyerOrdersRequest")
	proto.RegisterType((*PagingSellerOrdersRequest)(nil), "PagingSellerOrdersRequest")
	proto.RegisterType((*PagingBuyerAfterSalesOrderListResponse)(nil), "PagingBuyerAfterSalesOrderListResponse")
	proto.RegisterType((*PagingSellerAfterSalesOrderListResponse)(nil), "PagingSellerAfterSalesOrderListResponse")
	proto.RegisterType((*SAfterSalesOrder)(nil), "SAfterSalesOrder")
	proto.RegisterType((*SPagingBuyerAfterSalesOrder)(nil), "SPagingBuyerAfterSalesOrder")
	proto.RegisterType((*SPagingSellerAfterSalesOrder)(nil), "SPagingSellerAfterSalesOrder")
	proto.RegisterType((*ExchangeShipmentRequest)(nil), "ExchangeShipmentRequest")
	proto.RegisterEnum("EAfterSalesType", EAfterSalesType_name, EAfterSalesType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AfterSalesServiceClient is the client API for AfterSalesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AfterSalesServiceClient interface {
	// 提交售后单
	SubmitAfterSalesOrder(ctx context.Context, in *SubmitAfterSalesOrderRequest, opts ...grpc.CallOption) (*SubmitAfterSalesOrderResponse, error)
	// 获取订单的所有售后单,orderId
	GetAllAfterSalesOrderOfSaleOrder(ctx context.Context, in *OriginOrderIdRequest, opts ...grpc.CallOption) (*AfterSalesOrderListResponse, error)
	// 获取会员的分页售后单
	QueryPagerAfterSalesOrderOfMember(ctx context.Context, in *PagingBuyerOrdersRequest, opts ...grpc.CallOption) (*PagingBuyerAfterSalesOrderListResponse, error)
	// 获取商户的分页售后单
	QueryPagerAfterSalesOrderOfVendor(ctx context.Context, in *PagingSellerOrdersRequest, opts ...grpc.CallOption) (*PagingSellerAfterSalesOrderListResponse, error)
	// 获取售后单
	GetAfterSaleOrder(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*SAfterSalesOrder, error)
	// 同意售后
	AgreeAfterSales(ctx context.Context, in *IdAndRemark, opts ...grpc.CallOption) (*Result, error)
	// 拒绝售后
	DeclineAfterSales(ctx context.Context, in *IdAndRemark, opts ...grpc.CallOption) (*Result, error)
	// 申请调解
	RequestIntercede(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error)
	// 系统确认
	ConfirmAfterSales(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error)
	// 系统退回
	RejectAfterSales(ctx context.Context, in *IdAndRemark, opts ...grpc.CallOption) (*Result, error)
	// 处理退款/退货完成,一般是系统自动调用
	ProcessAfterSalesOrder(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error)
	// 售后收货
	ReceiveReturnShipment(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error)
	// 换货发货
	ExchangeShipment(ctx context.Context, in *ExchangeShipmentRequest, opts ...grpc.CallOption) (*Result, error)
	// 换货收货
	ReceiveExchange(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error)
}

type afterSalesServiceClient struct {
	cc *grpc.ClientConn
}

func NewAfterSalesServiceClient(cc *grpc.ClientConn) AfterSalesServiceClient {
	return &afterSalesServiceClient{cc}
}

func (c *afterSalesServiceClient) SubmitAfterSalesOrder(ctx context.Context, in *SubmitAfterSalesOrderRequest, opts ...grpc.CallOption) (*SubmitAfterSalesOrderResponse, error) {
	out := new(SubmitAfterSalesOrderResponse)
	err := c.cc.Invoke(ctx, "/AfterSalesService/SubmitAfterSalesOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) GetAllAfterSalesOrderOfSaleOrder(ctx context.Context, in *OriginOrderIdRequest, opts ...grpc.CallOption) (*AfterSalesOrderListResponse, error) {
	out := new(AfterSalesOrderListResponse)
	err := c.cc.Invoke(ctx, "/AfterSalesService/GetAllAfterSalesOrderOfSaleOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) QueryPagerAfterSalesOrderOfMember(ctx context.Context, in *PagingBuyerOrdersRequest, opts ...grpc.CallOption) (*PagingBuyerAfterSalesOrderListResponse, error) {
	out := new(PagingBuyerAfterSalesOrderListResponse)
	err := c.cc.Invoke(ctx, "/AfterSalesService/QueryPagerAfterSalesOrderOfMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) QueryPagerAfterSalesOrderOfVendor(ctx context.Context, in *PagingSellerOrdersRequest, opts ...grpc.CallOption) (*PagingSellerAfterSalesOrderListResponse, error) {
	out := new(PagingSellerAfterSalesOrderListResponse)
	err := c.cc.Invoke(ctx, "/AfterSalesService/QueryPagerAfterSalesOrderOfVendor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) GetAfterSaleOrder(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*SAfterSalesOrder, error) {
	out := new(SAfterSalesOrder)
	err := c.cc.Invoke(ctx, "/AfterSalesService/GetAfterSaleOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) AgreeAfterSales(ctx context.Context, in *IdAndRemark, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/AgreeAfterSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) DeclineAfterSales(ctx context.Context, in *IdAndRemark, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/DeclineAfterSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) RequestIntercede(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/RequestIntercede", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) ConfirmAfterSales(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/ConfirmAfterSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) RejectAfterSales(ctx context.Context, in *IdAndRemark, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/RejectAfterSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) ProcessAfterSalesOrder(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/ProcessAfterSalesOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) ReceiveReturnShipment(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/ReceiveReturnShipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) ExchangeShipment(ctx context.Context, in *ExchangeShipmentRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/ExchangeShipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afterSalesServiceClient) ReceiveExchange(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AfterSalesService/ReceiveExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AfterSalesServiceServer is the server API for AfterSalesService service.
type AfterSalesServiceServer interface {
	// 提交售后单
	SubmitAfterSalesOrder(context.Context, *SubmitAfterSalesOrderRequest) (*SubmitAfterSalesOrderResponse, error)
	// 获取订单的所有售后单,orderId
	GetAllAfterSalesOrderOfSaleOrder(context.Context, *OriginOrderIdRequest) (*AfterSalesOrderListResponse, error)
	// 获取会员的分页售后单
	QueryPagerAfterSalesOrderOfMember(context.Context, *PagingBuyerOrdersRequest) (*PagingBuyerAfterSalesOrderListResponse, error)
	// 获取商户的分页售后单
	QueryPagerAfterSalesOrderOfVendor(context.Context, *PagingSellerOrdersRequest) (*PagingSellerAfterSalesOrderListResponse, error)
	// 获取售后单
	GetAfterSaleOrder(context.Context, *Int64) (*SAfterSalesOrder, error)
	// 同意售后
	AgreeAfterSales(context.Context, *IdAndRemark) (*Result, error)
	// 拒绝售后
	DeclineAfterSales(context.Context, *IdAndRemark) (*Result, error)
	// 申请调解
	RequestIntercede(context.Context, *Int64) (*Result, error)
	// 系统确认
	ConfirmAfterSales(context.Context, *Int64) (*Result, error)
	// 系统退回
	RejectAfterSales(context.Context, *IdAndRemark) (*Result, error)
	// 处理退款/退货完成,一般是系统自动调用
	ProcessAfterSalesOrder(context.Context, *Int64) (*Result, error)
	// 售后收货
	ReceiveReturnShipment(context.Context, *Int64) (*Result, error)
	// 换货发货
	ExchangeShipment(context.Context, *ExchangeShipmentRequest) (*Result, error)
	// 换货收货
	ReceiveExchange(context.Context, *Int64) (*Result, error)
}

func RegisterAfterSalesServiceServer(s *grpc.Server, srv AfterSalesServiceServer) {
	s.RegisterService(&_AfterSalesService_serviceDesc, srv)
}

func _AfterSalesService_SubmitAfterSalesOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAfterSalesOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).SubmitAfterSalesOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/SubmitAfterSalesOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).SubmitAfterSalesOrder(ctx, req.(*SubmitAfterSalesOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_GetAllAfterSalesOrderOfSaleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).GetAllAfterSalesOrderOfSaleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/GetAllAfterSalesOrderOfSaleOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).GetAllAfterSalesOrderOfSaleOrder(ctx, req.(*OriginOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_QueryPagerAfterSalesOrderOfMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagingBuyerOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).QueryPagerAfterSalesOrderOfMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/QueryPagerAfterSalesOrderOfMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).QueryPagerAfterSalesOrderOfMember(ctx, req.(*PagingBuyerOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_QueryPagerAfterSalesOrderOfVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagingSellerOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).QueryPagerAfterSalesOrderOfVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/QueryPagerAfterSalesOrderOfVendor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).QueryPagerAfterSalesOrderOfVendor(ctx, req.(*PagingSellerOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_GetAfterSaleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).GetAfterSaleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/GetAfterSaleOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).GetAfterSaleOrder(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_AgreeAfterSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndRemark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).AgreeAfterSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/AgreeAfterSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).AgreeAfterSales(ctx, req.(*IdAndRemark))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_DeclineAfterSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndRemark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).DeclineAfterSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/DeclineAfterSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).DeclineAfterSales(ctx, req.(*IdAndRemark))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_RequestIntercede_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).RequestIntercede(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/RequestIntercede",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).RequestIntercede(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_ConfirmAfterSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).ConfirmAfterSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/ConfirmAfterSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).ConfirmAfterSales(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_RejectAfterSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndRemark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).RejectAfterSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/RejectAfterSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).RejectAfterSales(ctx, req.(*IdAndRemark))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_ProcessAfterSalesOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).ProcessAfterSalesOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/ProcessAfterSalesOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).ProcessAfterSalesOrder(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_ReceiveReturnShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).ReceiveReturnShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/ReceiveReturnShipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).ReceiveReturnShipment(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_ExchangeShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).ExchangeShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/ExchangeShipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).ExchangeShipment(ctx, req.(*ExchangeShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfterSalesService_ReceiveExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfterSalesServiceServer).ReceiveExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AfterSalesService/ReceiveExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfterSalesServiceServer).ReceiveExchange(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

var _AfterSalesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AfterSalesService",
	HandlerType: (*AfterSalesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAfterSalesOrder",
			Handler:    _AfterSalesService_SubmitAfterSalesOrder_Handler,
		},
		{
			MethodName: "GetAllAfterSalesOrderOfSaleOrder",
			Handler:    _AfterSalesService_GetAllAfterSalesOrderOfSaleOrder_Handler,
		},
		{
			MethodName: "QueryPagerAfterSalesOrderOfMember",
			Handler:    _AfterSalesService_QueryPagerAfterSalesOrderOfMember_Handler,
		},
		{
			MethodName: "QueryPagerAfterSalesOrderOfVendor",
			Handler:    _AfterSalesService_QueryPagerAfterSalesOrderOfVendor_Handler,
		},
		{
			MethodName: "GetAfterSaleOrder",
			Handler:    _AfterSalesService_GetAfterSaleOrder_Handler,
		},
		{
			MethodName: "AgreeAfterSales",
			Handler:    _AfterSalesService_AgreeAfterSales_Handler,
		},
		{
			MethodName: "DeclineAfterSales",
			Handler:    _AfterSalesService_DeclineAfterSales_Handler,
		},
		{
			MethodName: "RequestIntercede",
			Handler:    _AfterSalesService_RequestIntercede_Handler,
		},
		{
			MethodName: "ConfirmAfterSales",
			Handler:    _AfterSalesService_ConfirmAfterSales_Handler,
		},
		{
			MethodName: "RejectAfterSales",
			Handler:    _AfterSalesService_RejectAfterSales_Handler,
		},
		{
			MethodName: "ProcessAfterSalesOrder",
			Handler:    _AfterSalesService_ProcessAfterSalesOrder_Handler,
		},
		{
			MethodName: "ReceiveReturnShipment",
			Handler:    _AfterSalesService_ReceiveReturnShipment_Handler,
		},
		{
			MethodName: "ExchangeShipment",
			Handler:    _AfterSalesService_ExchangeShipment_Handler,
		},
		{
			MethodName: "ReceiveExchange",
			Handler:    _AfterSalesService_ReceiveExchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aftersales_service.proto",
}

func init() {
	proto.RegisterFile("aftersales_service.proto", fileDescriptor_aftersales_service_5dce44e64309fdd8)
}

var fileDescriptor_aftersales_service_5dce44e64309fdd8 = []byte{
	// 1123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0xd7, 0xcb, 0x72, 0x34, 0x92, 0x65, 0x7a, 0x13, 0xfb, 0xcf, 0xc8, 0x72, 0xe0, 0x3f, 0x91,
	0xda, 0x86, 0x53, 0x10, 0xae, 0x5b, 0xb4, 0x05, 0x72, 0xb2, 0x1d, 0xb7, 0x10, 0xd0, 0xc4, 0x0a,
	0x65, 0x07, 0x7d, 0x01, 0xc1, 0x5a, 0x1c, 0xd3, 0xac, 0xf9, 0x50, 0x97, 0xcb, 0x20, 0x3e, 0xf5,
	0xfb, 0x14, 0xe8, 0x77, 0xea, 0xb9, 0x9f, 0xa0, 0xc7, 0x62, 0x77, 0x49, 0x91, 0xa2, 0x1e, 0x51,
	0x2e, 0x3d, 0xf5, 0x24, 0xce, 0x6f, 0x86, 0x33, 0xbb, 0xf3, 0x9b, 0x19, 0x8e, 0x40, 0xa7, 0x37,
	0x1c, 0x59, 0x44, 0x3d, 0x8c, 0xde, 0x46, 0xc8, 0xde, 0xb9, 0x43, 0x34, 0x47, 0x2c, 0xe4, 0x61,
	0xa7, 0xe5, 0x78, 0xe1, 0x35, 0xf5, 0x94, 0x64, 0x1c, 0xc1, 0xa3, 0x0b, 0xe6, 0x3a, 0x6e, 0x70,
	0xc1, 0x6c, 0x64, 0x3d, 0xdb, 0xc2, 0x5f, 0x63, 0x8c, 0x38, 0xd1, 0x61, 0x35, 0x41, 0xf4, 0xf2,
	0x6e, 0xf9, 0xa0, 0x6a, 0xa5, 0xa2, 0xf1, 0x57, 0x19, 0xba, 0x83, 0xf8, 0xda, 0x77, 0xf9, 0x89,
	0x08, 0x31, 0x10, 0x21, 0xa4, 0xee, 0x83, 0xaf, 0x92, 0xaf, 0xa1, 0x9d, 0xbd, 0x73, 0x79, 0x3f,
	0x42, 0xbd, 0xb2, 0x5b, 0x3e, 0x68, 0x1f, 0x6b, 0xe6, 0xf9, 0x24, 0x6e, 0x15, 0xec, 0xc8, 0x1e,
	0xb4, 0x7b, 0x1c, 0xfd, 0x41, 0x40, 0x47, 0xd1, 0x6d, 0xc8, 0x7b, 0xb6, 0x5e, 0x95, 0xae, 0x0b,
	0x28, 0xe9, 0xc0, 0x83, 0xd7, 0x31, 0x0d, 0xb8, 0xcb, 0xef, 0xf5, 0x9a, 0xb4, 0x18, 0xcb, 0x64,
	0x0b, 0xea, 0x16, 0xd2, 0x28, 0x0c, 0xf4, 0x95, 0xdd, 0xf2, 0x41, 0xc3, 0x4a, 0x24, 0xf1, 0x4e,
	0xcf, 0xa7, 0x0e, 0x5e, 0x31, 0x4f, 0xaf, 0x4b, 0xcd, 0x58, 0x36, 0x7e, 0x83, 0x9d, 0x39, 0x77,
	0x8d, 0x46, 0x61, 0x10, 0xa1, 0xb8, 0xec, 0x39, 0x63, 0x67, 0xa1, 0x8d, 0xe9, 0x65, 0x13, 0x51,
	0x84, 0x3b, 0x67, 0xec, 0x65, 0xe4, 0xc8, 0x4b, 0x36, 0xac, 0x44, 0x22, 0x9f, 0xc2, 0x46, 0xc1,
	0xd9, 0xf8, 0x36, 0xd3, 0x0a, 0xe3, 0x1b, 0xd8, 0x2e, 0x80, 0xdf, 0xb9, 0x11, 0x1f, 0x87, 0xdf,
	0x87, 0x95, 0x37, 0xd4, 0x8b, 0x45, 0xf0, 0xea, 0x41, 0xf3, 0x78, 0xc3, 0x1c, 0x14, 0x0f, 0xaa,
	0xf4, 0xc6, 0xcf, 0xa0, 0xf7, 0xa9, 0xe3, 0x06, 0xce, 0x69, 0x7c, 0x8f, 0x4c, 0xaa, 0xa2, 0x1c,
	0x61, 0x12, 0xcd, 0x08, 0x4b, 0x44, 0xb2, 0x07, 0xf5, 0x3e, 0x65, 0xd4, 0x8f, 0xe4, 0x1d, 0x9a,
	0xc7, 0x6d, 0x73, 0xa0, 0xbc, 0x28, 0xd4, 0x4a, 0xb4, 0xc6, 0x5b, 0x78, 0xac, 0xf0, 0x01, 0x7a,
	0x5e, 0xd1, 0x7d, 0x07, 0x1e, 0x28, 0x78, 0xec, 0x7f, 0x2c, 0x2f, 0x1d, 0x60, 0x04, 0x7b, 0xb9,
	0xe3, 0x2f, 0xca, 0xc8, 0x23, 0x58, 0xb9, 0x0c, 0x39, 0xf5, 0x92, 0x50, 0x4a, 0x20, 0x47, 0x50,
	0x7b, 0x41, 0x39, 0xd5, 0x2b, 0x32, 0x4d, 0xdd, 0x34, 0xca, 0x2c, 0x6f, 0x96, 0xb4, 0x34, 0x18,
	0xec, 0xe7, 0xaf, 0xf4, 0xf1, 0x21, 0x3f, 0x9b, 0x08, 0xb9, 0x93, 0x86, 0x9c, 0xe9, 0x2e, 0x89,
	0xf9, 0x77, 0x0d, 0xb4, 0x22, 0x81, 0xa4, 0x0d, 0x95, 0x71, 0xe2, 0x2a, 0x3d, 0x9b, 0x3c, 0x85,
	0x35, 0x0b, 0x3d, 0xca, 0x31, 0xad, 0x9d, 0x8a, 0x54, 0x4d, 0x82, 0x22, 0xe9, 0x6f, 0x30, 0xb0,
	0xc3, 0xac, 0xb8, 0xc6, 0x72, 0x9e, 0xef, 0x5a, 0x91, 0xef, 0x62, 0x83, 0x8a, 0x56, 0x59, 0x99,
	0x6a, 0xc7, 0x27, 0x00, 0xb9, 0x56, 0xac, 0x4b, 0x27, 0x30, 0xa7, 0x0d, 0x57, 0xa5, 0x87, 0x59,
	0x6d, 0xf8, 0x60, 0x6e, 0x1b, 0x36, 0x26, 0xdb, 0x50, 0xc4, 0xeb, 0x23, 0x8b, 0xc2, 0xe0, 0x15,
	0xf5, 0x51, 0x07, 0xa9, 0xcd, 0x21, 0x64, 0x17, 0x9a, 0x4a, 0xea, 0xdf, 0x86, 0x01, 0xea, 0x4d,
	0x69, 0x90, 0x87, 0x88, 0x01, 0x2d, 0x0b, 0x79, 0xcc, 0x82, 0xc1, 0x48, 0xfa, 0x68, 0x49, 0x93,
	0x09, 0x4c, 0x65, 0x56, 0xc9, 0x32, 0x8d, 0xfa, 0x9a, 0x34, 0x9a, 0x04, 0xf3, 0x56, 0xf2, 0x7c,
	0x7a, 0x7b, 0xd2, 0x4a, 0x82, 0xea, 0x96, 0x3e, 0x65, 0x77, 0xfa, 0x7a, 0x7a, 0x4b, 0x21, 0x89,
	0x73, 0x28, 0x1e, 0x12, 0xad, 0xa6, 0xce, 0x91, 0xc7, 0x44, 0x3d, 0x0d, 0x38, 0xe5, 0xa8, 0x6f,
	0xc8, 0xd4, 0x29, 0x41, 0xe4, 0xe0, 0x8c, 0x21, 0xe5, 0x78, 0xe9, 0xfa, 0xa8, 0x13, 0x95, 0xf3,
	0x0c, 0x11, 0xfa, 0xab, 0x91, 0x9d, 0xea, 0x1f, 0x2a, 0x7d, 0x86, 0x90, 0x2e, 0x34, 0xa4, 0xa3,
	0x4b, 0x7c, 0xcf, 0xf5, 0x47, 0x32, 0x6c, 0x06, 0x18, 0x7f, 0x54, 0x61, 0x7b, 0x41, 0x53, 0x4c,
	0x55, 0x61, 0x3a, 0xe4, 0x5f, 0x85, 0xc9, 0x78, 0x4b, 0xc5, 0x85, 0x95, 0x27, 0xea, 0x46, 0xd6,
	0xbf, 0xe4, 0xa0, 0xa6, 0x78, 0xcc, 0x90, 0x7f, 0xa5, 0xfe, 0x44, 0x76, 0xef, 0xe2, 0x9e, 0x2d,
	0xcb, 0xaf, 0x6a, 0x29, 0x41, 0x64, 0x47, 0x7c, 0x4a, 0x2e, 0x5d, 0xee, 0x61, 0x52, 0x7e, 0x19,
	0x90, 0x6a, 0x15, 0xdf, 0x90, 0x69, 0x15, 0xd7, 0x63, 0xbe, 0x9a, 0xf3, 0xf9, 0x6a, 0x7d, 0x80,
	0xaf, 0xb5, 0xc5, 0x7c, 0xb5, 0x8b, 0x7c, 0xfd, 0x5e, 0x85, 0xee, 0xa2, 0x89, 0xf2, 0x11, 0x84,
	0xe5, 0xc6, 0x41, 0x75, 0x72, 0x1c, 0x74, 0xa1, 0x21, 0x1f, 0x73, 0x6c, 0x65, 0xc0, 0x7f, 0x64,
	0x2d, 0x4d, 0xd6, 0x4f, 0xf0, 0xbf, 0xf3, 0xf7, 0xc3, 0x5b, 0x1a, 0x38, 0x38, 0xb8, 0x75, 0x47,
	0x3e, 0x06, 0x3c, 0xfd, 0x38, 0x16, 0x69, 0xda, 0x82, 0x7a, 0x32, 0xa1, 0x92, 0xad, 0x21, 0x99,
	0x4d, 0x3a, 0xac, 0xa6, 0x53, 0xa9, 0xaa, 0xe8, 0x4b, 0xc4, 0xc3, 0x21, 0xac, 0x17, 0xb6, 0x27,
	0xb2, 0x06, 0x0d, 0xf1, 0x7b, 0x15, 0x44, 0xc8, 0xb5, 0x12, 0x69, 0x03, 0xc8, 0xa5, 0x0a, 0x6f,
	0xe2, 0xc0, 0xd6, 0xca, 0x99, 0x2c, 0x06, 0x96, 0x56, 0x21, 0x1a, 0xb4, 0x84, 0x9c, 0x1e, 0x51,
	0xab, 0x92, 0x75, 0x68, 0x0a, 0x64, 0xa0, 0x16, 0x47, 0xad, 0x76, 0xfc, 0x67, 0x3d, 0xbf, 0xb5,
	0x24, 0x38, 0xf9, 0x1e, 0x36, 0x67, 0x6e, 0x47, 0x64, 0xc7, 0x5c, 0xb4, 0x21, 0x76, 0x9e, 0x98,
	0x0b, 0x97, 0x2a, 0xa3, 0x44, 0x7e, 0x80, 0xdd, 0x6f, 0x91, 0x9f, 0x78, 0x5e, 0xc1, 0xe4, 0xe2,
	0x46, 0x3c, 0xab, 0x20, 0x9b, 0xe6, 0xac, 0xcd, 0xb5, 0xd3, 0x35, 0x17, 0x7c, 0xab, 0x8d, 0x12,
	0x71, 0xe1, 0xff, 0xaf, 0x63, 0x64, 0xf7, 0x7d, 0xea, 0x4c, 0x75, 0xcd, 0xc5, 0xcd, 0x4b, 0xf4,
	0xaf, 0x91, 0x91, 0xc7, 0xe6, 0xbc, 0x6d, 0xa9, 0xb3, 0x6f, 0x2e, 0xb7, 0x89, 0x18, 0x25, 0x72,
	0xb7, 0x30, 0x94, 0x9a, 0x8a, 0xa4, 0x63, 0xce, 0x5d, 0x9d, 0x3a, 0x07, 0xe6, 0x92, 0x3b, 0x88,
	0x51, 0x22, 0x47, 0xb0, 0x21, 0x52, 0x96, 0xda, 0xa8, 0x1c, 0xd5, 0xcd, 0x5e, 0xc0, 0xbf, 0xfc,
	0xa2, 0x33, 0xbd, 0x18, 0x1a, 0x25, 0x72, 0x08, 0xeb, 0x27, 0x0e, 0x43, 0xcc, 0x34, 0xa4, 0x65,
	0xf6, 0xec, 0x93, 0xc0, 0x56, 0x1f, 0xa2, 0xce, 0xaa, 0x69, 0x61, 0x14, 0x7b, 0xdc, 0x28, 0x89,
	0xad, 0xf5, 0x05, 0x0e, 0x3d, 0x37, 0x58, 0xca, 0xfa, 0x13, 0xd0, 0x92, 0x2b, 0xf4, 0x02, 0x8e,
	0x6c, 0x88, 0x36, 0x8e, 0x8f, 0x92, 0x33, 0xdb, 0x83, 0x8d, 0xb3, 0x30, 0xb8, 0x71, 0x99, 0x9f,
	0x73, 0x3a, 0xc3, 0xee, 0x99, 0x70, 0xf7, 0x0b, 0x0e, 0xf9, 0x32, 0xb1, 0x9f, 0xc1, 0x56, 0x9f,
	0x85, 0x43, 0x8c, 0xa2, 0x62, 0x55, 0xce, 0xf0, 0x7c, 0x08, 0x9b, 0x16, 0x0e, 0xd1, 0x7d, 0x97,
	0x74, 0x43, 0xda, 0x9e, 0xb3, 0x6c, 0xbf, 0x02, 0xad, 0xd8, 0xc5, 0x44, 0x37, 0xe7, 0x34, 0x76,
	0xfe, 0xc5, 0xa7, 0xb0, 0x9e, 0x04, 0x49, 0x8d, 0x67, 0xb8, 0x3f, 0x7d, 0x0e, 0x0f, 0x87, 0xa1,
	0x6f, 0x3a, 0x2e, 0xbf, 0x8d, 0xaf, 0x4d, 0x27, 0x3c, 0x0e, 0x4d, 0x36, 0x1a, 0x9e, 0x6e, 0x4f,
	0xb5, 0xdd, 0x45, 0xcc, 0x91, 0x9d, 0x79, 0x34, 0x8a, 0x7e, 0x5c, 0x35, 0x9f, 0xcb, 0xbf, 0x71,
	0xd7, 0x75, 0xf9, 0xf3, 0xf9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0x51, 0x5e, 0x80, 0xf7,
	0x0d, 0x00, 0x00,
}
