// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/cart.proto

package proto // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WsCartRequest struct {
	MemberId             int64             `protobuf:"zigzag64,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	Action               string            `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WsCartRequest) Reset()         { *m = WsCartRequest{} }
func (m *WsCartRequest) String() string { return proto.CompactTextString(m) }
func (*WsCartRequest) ProtoMessage()    {}
func (*WsCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_b0150761447ab157, []int{0}
}
func (m *WsCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WsCartRequest.Unmarshal(m, b)
}
func (m *WsCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WsCartRequest.Marshal(b, m, deterministic)
}
func (dst *WsCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WsCartRequest.Merge(dst, src)
}
func (m *WsCartRequest) XXX_Size() int {
	return xxx_messageInfo_WsCartRequest.Size(m)
}
func (m *WsCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WsCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WsCartRequest proto.InternalMessageInfo

func (m *WsCartRequest) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *WsCartRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *WsCartRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type NormalCartRequest struct {
	MemberId             int64             `protobuf:"zigzag64,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	Action               string            `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NormalCartRequest) Reset()         { *m = NormalCartRequest{} }
func (m *NormalCartRequest) String() string { return proto.CompactTextString(m) }
func (*NormalCartRequest) ProtoMessage()    {}
func (*NormalCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_b0150761447ab157, []int{1}
}
func (m *NormalCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalCartRequest.Unmarshal(m, b)
}
func (m *NormalCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalCartRequest.Marshal(b, m, deterministic)
}
func (dst *NormalCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalCartRequest.Merge(dst, src)
}
func (m *NormalCartRequest) XXX_Size() int {
	return xxx_messageInfo_NormalCartRequest.Size(m)
}
func (m *NormalCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NormalCartRequest proto.InternalMessageInfo

func (m *NormalCartRequest) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *NormalCartRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *NormalCartRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

// 购物车
type SShoppingCart struct {
	// 编号
	CartId int32 `protobuf:"zigzag32,1,opt,name=CartId,proto3" json:"CartId,omitempty"`
	// 购物车KEY
	Code string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	// 店铺分组
	Shops                []*SShoppingCartGroup `protobuf:"bytes,3,rep,name=Shops,proto3" json:"Shops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SShoppingCart) Reset()         { *m = SShoppingCart{} }
func (m *SShoppingCart) String() string { return proto.CompactTextString(m) }
func (*SShoppingCart) ProtoMessage()    {}
func (*SShoppingCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_b0150761447ab157, []int{2}
}
func (m *SShoppingCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SShoppingCart.Unmarshal(m, b)
}
func (m *SShoppingCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SShoppingCart.Marshal(b, m, deterministic)
}
func (dst *SShoppingCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SShoppingCart.Merge(dst, src)
}
func (m *SShoppingCart) XXX_Size() int {
	return xxx_messageInfo_SShoppingCart.Size(m)
}
func (m *SShoppingCart) XXX_DiscardUnknown() {
	xxx_messageInfo_SShoppingCart.DiscardUnknown(m)
}

var xxx_messageInfo_SShoppingCart proto.InternalMessageInfo

func (m *SShoppingCart) GetCartId() int32 {
	if m != nil {
		return m.CartId
	}
	return 0
}

func (m *SShoppingCart) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SShoppingCart) GetShops() []*SShoppingCartGroup {
	if m != nil {
		return m.Shops
	}
	return nil
}

// 购物车店铺分组
type SShoppingCartGroup struct {
	// 店铺编号
	ShopId int64 `protobuf:"zigzag64,1,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
	// 供货商编号
	VendorId int64 `protobuf:"zigzag64,2,opt,name=VendorId,proto3" json:"VendorId,omitempty"`
	// 店铺名称
	ShopName string `protobuf:"bytes,3,opt,name=ShopName,proto3" json:"ShopName,omitempty"`
	// 是否结算
	Checked bool `protobuf:"varint,4,opt,name=Checked,proto3" json:"Checked,omitempty"`
	// 商品
	Items                []*SShoppingCartItem `protobuf:"bytes,5,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SShoppingCartGroup) Reset()         { *m = SShoppingCartGroup{} }
func (m *SShoppingCartGroup) String() string { return proto.CompactTextString(m) }
func (*SShoppingCartGroup) ProtoMessage()    {}
func (*SShoppingCartGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_b0150761447ab157, []int{3}
}
func (m *SShoppingCartGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SShoppingCartGroup.Unmarshal(m, b)
}
func (m *SShoppingCartGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SShoppingCartGroup.Marshal(b, m, deterministic)
}
func (dst *SShoppingCartGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SShoppingCartGroup.Merge(dst, src)
}
func (m *SShoppingCartGroup) XXX_Size() int {
	return xxx_messageInfo_SShoppingCartGroup.Size(m)
}
func (m *SShoppingCartGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SShoppingCartGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SShoppingCartGroup proto.InternalMessageInfo

func (m *SShoppingCartGroup) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *SShoppingCartGroup) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *SShoppingCartGroup) GetShopName() string {
	if m != nil {
		return m.ShopName
	}
	return ""
}

func (m *SShoppingCartGroup) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

func (m *SShoppingCartGroup) GetItems() []*SShoppingCartItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 购物车商品勾选
type SCheckCartItem struct {
	// 商品编号
	ItemId int64 `protobuf:"zigzag64,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	// SKU编号
	SkuId int64 `protobuf:"zigzag64,2,opt,name=SkuId,proto3" json:"SkuId,omitempty"`
	// 是否勾选
	Checked              bool     `protobuf:"varint,3,opt,name=Checked,proto3" json:"Checked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCheckCartItem) Reset()         { *m = SCheckCartItem{} }
func (m *SCheckCartItem) String() string { return proto.CompactTextString(m) }
func (*SCheckCartItem) ProtoMessage()    {}
func (*SCheckCartItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_b0150761447ab157, []int{4}
}
func (m *SCheckCartItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCheckCartItem.Unmarshal(m, b)
}
func (m *SCheckCartItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCheckCartItem.Marshal(b, m, deterministic)
}
func (dst *SCheckCartItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCheckCartItem.Merge(dst, src)
}
func (m *SCheckCartItem) XXX_Size() int {
	return xxx_messageInfo_SCheckCartItem.Size(m)
}
func (m *SCheckCartItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SCheckCartItem.DiscardUnknown(m)
}

var xxx_messageInfo_SCheckCartItem proto.InternalMessageInfo

func (m *SCheckCartItem) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *SCheckCartItem) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *SCheckCartItem) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

// 购物车商品操作响应
type CartItemResponse struct {
	ErrCode              int64              `protobuf:"varint,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string             `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Item                 *SShoppingCartItem `protobuf:"bytes,3,opt,name=Item,proto3" json:"Item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CartItemResponse) Reset()         { *m = CartItemResponse{} }
func (m *CartItemResponse) String() string { return proto.CompactTextString(m) }
func (*CartItemResponse) ProtoMessage()    {}
func (*CartItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_b0150761447ab157, []int{5}
}
func (m *CartItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItemResponse.Unmarshal(m, b)
}
func (m *CartItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItemResponse.Marshal(b, m, deterministic)
}
func (dst *CartItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItemResponse.Merge(dst, src)
}
func (m *CartItemResponse) XXX_Size() int {
	return xxx_messageInfo_CartItemResponse.Size(m)
}
func (m *CartItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CartItemResponse proto.InternalMessageInfo

func (m *CartItemResponse) GetErrCode() int64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CartItemResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CartItemResponse) GetItem() *SShoppingCartItem {
	if m != nil {
		return m.Item
	}
	return nil
}

// 购物车商品
type SShoppingCartItem struct {
	// 商品编号
	ItemId int64 `protobuf:"zigzag64,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	// SKU编号
	SkuId int64 `protobuf:"zigzag64,2,opt,name=SkuId,proto3" json:"SkuId,omitempty"`
	// 商品标题
	Title string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	// 商品图片
	Image string `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`
	// 规格文本
	SpecWord string `protobuf:"bytes,5,opt,name=SpecWord,proto3" json:"SpecWord,omitempty"`
	// 商品编码
	Code string `protobuf:"bytes,6,opt,name=Code,proto3" json:"Code,omitempty"`
	// 零售价
	RetailPrice float64 `protobuf:"fixed64,7,opt,name=RetailPrice,proto3" json:"RetailPrice,omitempty"`
	// 销售价
	Price float64 `protobuf:"fixed64,8,opt,name=Price,proto3" json:"Price,omitempty"`
	// 数量
	Quantity int32 `protobuf:"zigzag32,9,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	// 是否结算
	Checked bool `protobuf:"varint,10,opt,name=Checked,proto3" json:"Checked,omitempty"`
	// 库存文本
	StockText string `protobuf:"bytes,11,opt,name=StockText,proto3" json:"StockText,omitempty"`
	// 店铺编号
	ShopId               int64    `protobuf:"zigzag64,12,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SShoppingCartItem) Reset()         { *m = SShoppingCartItem{} }
func (m *SShoppingCartItem) String() string { return proto.CompactTextString(m) }
func (*SShoppingCartItem) ProtoMessage()    {}
func (*SShoppingCartItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_b0150761447ab157, []int{6}
}
func (m *SShoppingCartItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SShoppingCartItem.Unmarshal(m, b)
}
func (m *SShoppingCartItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SShoppingCartItem.Marshal(b, m, deterministic)
}
func (dst *SShoppingCartItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SShoppingCartItem.Merge(dst, src)
}
func (m *SShoppingCartItem) XXX_Size() int {
	return xxx_messageInfo_SShoppingCartItem.Size(m)
}
func (m *SShoppingCartItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SShoppingCartItem.DiscardUnknown(m)
}

var xxx_messageInfo_SShoppingCartItem proto.InternalMessageInfo

func (m *SShoppingCartItem) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *SShoppingCartItem) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *SShoppingCartItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SShoppingCartItem) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *SShoppingCartItem) GetSpecWord() string {
	if m != nil {
		return m.SpecWord
	}
	return ""
}

func (m *SShoppingCartItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SShoppingCartItem) GetRetailPrice() float64 {
	if m != nil {
		return m.RetailPrice
	}
	return 0
}

func (m *SShoppingCartItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SShoppingCartItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SShoppingCartItem) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

func (m *SShoppingCartItem) GetStockText() string {
	if m != nil {
		return m.StockText
	}
	return ""
}

func (m *SShoppingCartItem) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func init() {
	proto.RegisterType((*WsCartRequest)(nil), "WsCartRequest")
	proto.RegisterMapType((map[string]string)(nil), "WsCartRequest.DataEntry")
	proto.RegisterType((*NormalCartRequest)(nil), "NormalCartRequest")
	proto.RegisterMapType((map[string]string)(nil), "NormalCartRequest.DataEntry")
	proto.RegisterType((*SShoppingCart)(nil), "SShoppingCart")
	proto.RegisterType((*SShoppingCartGroup)(nil), "SShoppingCartGroup")
	proto.RegisterType((*SCheckCartItem)(nil), "SCheckCartItem")
	proto.RegisterType((*CartItemResponse)(nil), "CartItemResponse")
	proto.RegisterType((*SShoppingCartItem)(nil), "SShoppingCartItem")
}

func init() { proto.RegisterFile("message/cart.proto", fileDescriptor_cart_b0150761447ab157) }

var fileDescriptor_cart_b0150761447ab157 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x8f, 0x93, 0x40,
	0x14, 0xc7, 0x43, 0x29, 0xdb, 0xf2, 0xea, 0x9a, 0xed, 0xec, 0xc6, 0x4c, 0x36, 0x1b, 0x43, 0x38,
	0x18, 0x4c, 0x0c, 0x9a, 0xf5, 0xa0, 0xd1, 0x9b, 0xb5, 0x31, 0x3d, 0xb8, 0xd1, 0xe9, 0xc6, 0x35,
	0xde, 0xa6, 0x30, 0x52, 0x52, 0x60, 0x70, 0x18, 0x8c, 0xfd, 0x46, 0xc6, 0xa3, 0xdf, 0xc0, 0x6f,
	0x66, 0x66, 0x06, 0x58, 0x48, 0xbd, 0x18, 0x3d, 0x0d, 0xbf, 0xf7, 0x1e, 0xef, 0xfd, 0xf9, 0xcf,
	0x0b, 0x80, 0x72, 0x56, 0x55, 0x34, 0x61, 0x8f, 0x23, 0x2a, 0x64, 0x58, 0x0a, 0x2e, 0xb9, 0xff,
	0xc3, 0x82, 0xe3, 0x9b, 0x6a, 0x41, 0x85, 0x24, 0xec, 0x4b, 0xcd, 0x2a, 0x89, 0xce, 0x61, 0x9a,
	0xb3, 0x7c, 0xc3, 0xc4, 0x2a, 0xc6, 0x96, 0x67, 0x05, 0x88, 0x74, 0x8c, 0xee, 0xc1, 0x11, 0x8d,
	0x64, 0xca, 0x0b, 0x3c, 0xf2, 0xac, 0xc0, 0x25, 0x0d, 0xa1, 0x47, 0x30, 0x8e, 0xa9, 0xa4, 0xd8,
	0xf6, 0xec, 0x60, 0x76, 0x89, 0xc3, 0x41, 0xc7, 0xf0, 0x35, 0x95, 0x74, 0x59, 0x48, 0xb1, 0x27,
	0xba, 0xea, 0xfc, 0x19, 0xb8, 0x5d, 0x08, 0x9d, 0x80, 0xbd, 0x63, 0x7b, 0x3d, 0xc9, 0x25, 0xea,
	0x11, 0x9d, 0x81, 0xf3, 0x95, 0x66, 0x35, 0x6b, 0x66, 0x18, 0x78, 0x31, 0x7a, 0x6e, 0xf9, 0x3f,
	0x2d, 0x98, 0x5f, 0x71, 0x91, 0xd3, 0xec, 0x5f, 0x05, 0x3f, 0x19, 0x08, 0xbe, 0x08, 0x0f, 0xba,
	0xfe, 0x3f, 0xd1, 0x9f, 0xe1, 0x78, 0xbd, 0xde, 0xf2, 0xb2, 0x4c, 0x8b, 0x44, 0x0d, 0x50, 0x9a,
	0xd4, 0xd9, 0xa8, 0x9d, 0x93, 0x86, 0x10, 0x82, 0xf1, 0x82, 0xc7, 0x6d, 0x07, 0xfd, 0x8c, 0x1e,
	0x82, 0xa3, 0xde, 0xad, 0x1a, 0xa1, 0xa7, 0xe1, 0xa0, 0xd5, 0x1b, 0xc1, 0xeb, 0x92, 0x98, 0x0a,
	0xff, 0xbb, 0x05, 0xe8, 0x30, 0xab, 0xa6, 0xa9, 0x60, 0xe7, 0x4d, 0x43, 0xca, 0xb5, 0x0f, 0xac,
	0x88, 0xb9, 0x72, 0x6d, 0x64, 0x5c, 0x6b, 0x59, 0xe5, 0x54, 0xd5, 0x15, 0xcd, 0x19, 0xb6, 0xb5,
	0x9a, 0x8e, 0x11, 0x86, 0xc9, 0x62, 0xcb, 0xa2, 0x1d, 0x8b, 0xf1, 0xd8, 0xb3, 0x82, 0x29, 0x69,
	0x11, 0x05, 0xe0, 0xac, 0x24, 0xcb, 0x2b, 0xec, 0x68, 0xad, 0x68, 0xa8, 0x55, 0xa5, 0x88, 0x29,
	0xf0, 0x3f, 0xc2, 0xdd, 0xb5, 0x7e, 0xab, 0x4d, 0x28, 0x95, 0xea, 0xbc, 0x55, 0x69, 0x48, 0xd9,
	0xba, 0xde, 0xd5, 0x9d, 0x44, 0x03, 0x7d, 0x0d, 0xf6, 0x40, 0x83, 0x9f, 0xc1, 0x49, 0x37, 0x8c,
	0x55, 0x25, 0x2f, 0x2a, 0xad, 0x78, 0x29, 0x84, 0xb6, 0x56, 0x35, 0xb7, 0x49, 0x8b, 0x6a, 0xea,
	0x52, 0x88, 0xb7, 0x55, 0xd2, 0x6e, 0x87, 0x21, 0xf4, 0x00, 0xc6, 0xaa, 0x83, 0x6e, 0xfe, 0xe7,
	0x0f, 0xd1, 0x79, 0xff, 0xd7, 0x08, 0xe6, 0x07, 0xb9, 0xbf, 0xfc, 0x96, 0x33, 0x70, 0xae, 0x53,
	0x99, 0xb5, 0x46, 0x1b, 0x50, 0xd1, 0x55, 0x4e, 0x13, 0xa6, 0x3d, 0x76, 0x89, 0x01, 0x7d, 0x2f,
	0x25, 0x8b, 0x6e, 0xb8, 0x88, 0xb1, 0xd3, 0xdc, 0x4b, 0xc3, 0xdd, 0xf6, 0x1c, 0xf5, 0xb6, 0xc7,
	0x83, 0x19, 0x61, 0x92, 0xa6, 0xd9, 0x3b, 0x91, 0x46, 0x0c, 0x4f, 0x3c, 0x2b, 0xb0, 0x48, 0x3f,
	0xa4, 0xe6, 0x98, 0xdc, 0x54, 0xe7, 0x0c, 0xa8, 0x39, 0xef, 0x6b, 0x5a, 0xc8, 0x54, 0xee, 0xb1,
	0xab, 0x77, 0xb4, 0xe3, 0xbe, 0xf7, 0x30, 0xbc, 0xff, 0x0b, 0x70, 0xd7, 0x92, 0x47, 0xbb, 0x6b,
	0xf6, 0x4d, 0xe2, 0x99, 0x96, 0x71, 0x1b, 0xe8, 0xed, 0xe1, 0x9d, 0xfe, 0x1e, 0xbe, 0xba, 0x0f,
	0xa7, 0x11, 0xcf, 0xc3, 0x24, 0x95, 0xdb, 0x7a, 0x13, 0x26, 0xfc, 0x92, 0x87, 0xa2, 0x8c, 0x3e,
	0x4d, 0xc2, 0x97, 0xfa, 0x07, 0xb5, 0x39, 0xd2, 0xc7, 0xd3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x72, 0x43, 0x65, 0x32, 0xbd, 0x04, 0x00, 0x00,
}
