// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_service.proto

package proto // import "./"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeleteProductRequest struct {
	SellerId             int64    `protobuf:"varint,1,opt,name=SellerId,proto3" json:"SellerId"`
	ProductId            int64    `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{0}
}
func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(dst, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetSellerId() int64 {
	if m != nil {
		return m.SellerId
	}
	return 0
}

func (m *DeleteProductRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type ProductId struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductId) Reset()         { *m = ProductId{} }
func (m *ProductId) String() string { return proto.CompactTextString(m) }
func (*ProductId) ProtoMessage()    {}
func (*ProductId) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{1}
}
func (m *ProductId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductId.Unmarshal(m, b)
}
func (m *ProductId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductId.Marshal(b, m, deterministic)
}
func (dst *ProductId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductId.Merge(dst, src)
}
func (m *ProductId) XXX_Size() int {
	return xxx_messageInfo_ProductId.Size(m)
}
func (m *ProductId) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductId.DiscardUnknown(m)
}

var xxx_messageInfo_ProductId proto.InternalMessageInfo

func (m *ProductId) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ProductModelId struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductModelId) Reset()         { *m = ProductModelId{} }
func (m *ProductModelId) String() string { return proto.CompactTextString(m) }
func (*ProductModelId) ProtoMessage()    {}
func (*ProductModelId) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{2}
}
func (m *ProductModelId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductModelId.Unmarshal(m, b)
}
func (m *ProductModelId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductModelId.Marshal(b, m, deterministic)
}
func (dst *ProductModelId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductModelId.Merge(dst, src)
}
func (m *ProductModelId) XXX_Size() int {
	return xxx_messageInfo_ProductModelId.Size(m)
}
func (m *ProductModelId) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductModelId.DiscardUnknown(m)
}

var xxx_messageInfo_ProductModelId proto.InternalMessageInfo

func (m *ProductModelId) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ProductAttrId struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductAttrId) Reset()         { *m = ProductAttrId{} }
func (m *ProductAttrId) String() string { return proto.CompactTextString(m) }
func (*ProductAttrId) ProtoMessage()    {}
func (*ProductAttrId) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{3}
}
func (m *ProductAttrId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAttrId.Unmarshal(m, b)
}
func (m *ProductAttrId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAttrId.Marshal(b, m, deterministic)
}
func (dst *ProductAttrId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAttrId.Merge(dst, src)
}
func (m *ProductAttrId) XXX_Size() int {
	return xxx_messageInfo_ProductAttrId.Size(m)
}
func (m *ProductAttrId) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAttrId.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAttrId proto.InternalMessageInfo

func (m *ProductAttrId) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ProductAttrItemId struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductAttrItemId) Reset()         { *m = ProductAttrItemId{} }
func (m *ProductAttrItemId) String() string { return proto.CompactTextString(m) }
func (*ProductAttrItemId) ProtoMessage()    {}
func (*ProductAttrItemId) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{4}
}
func (m *ProductAttrItemId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAttrItemId.Unmarshal(m, b)
}
func (m *ProductAttrItemId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAttrItemId.Marshal(b, m, deterministic)
}
func (dst *ProductAttrItemId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAttrItemId.Merge(dst, src)
}
func (m *ProductAttrItemId) XXX_Size() int {
	return xxx_messageInfo_ProductAttrItemId.Size(m)
}
func (m *ProductAttrItemId) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAttrItemId.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAttrItemId proto.InternalMessageInfo

func (m *ProductAttrItemId) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ProductModelListResponse struct {
	Value                []*SProductModel `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProductModelListResponse) Reset()         { *m = ProductModelListResponse{} }
func (m *ProductModelListResponse) String() string { return proto.CompactTextString(m) }
func (*ProductModelListResponse) ProtoMessage()    {}
func (*ProductModelListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{5}
}
func (m *ProductModelListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductModelListResponse.Unmarshal(m, b)
}
func (m *ProductModelListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductModelListResponse.Marshal(b, m, deterministic)
}
func (dst *ProductModelListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductModelListResponse.Merge(dst, src)
}
func (m *ProductModelListResponse) XXX_Size() int {
	return xxx_messageInfo_ProductModelListResponse.Size(m)
}
func (m *ProductModelListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductModelListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductModelListResponse proto.InternalMessageInfo

func (m *ProductModelListResponse) GetValue() []*SProductModel {
	if m != nil {
		return m.Value
	}
	return nil
}

// 产品模型
type SProductModel struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	// 属性字符
	AttrStr string `protobuf:"bytes,3,opt,name=AttrStr,proto3" json:"AttrStr"`
	// 规格字符
	SpecStr string `protobuf:"bytes,4,opt,name=SpecStr,proto3" json:"SpecStr"`
	// 属性
	Attrs []*SProductAttr `protobuf:"bytes,5,rep,name=Attrs,proto3" json:"Attrs"`
	// 规格
	Specs []*SProductSpec `protobuf:"bytes,6,rep,name=Specs,proto3" json:"Specs"`
	// 关联品牌
	Brands []*SProductBrand `protobuf:"bytes,7,rep,name=Brands,proto3" json:"Brands"`
	// 是否启用
	Enabled              int32    `protobuf:"varint,8,opt,name=Enabled,proto3" json:"Enabled"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SProductModel) Reset()         { *m = SProductModel{} }
func (m *SProductModel) String() string { return proto.CompactTextString(m) }
func (*SProductModel) ProtoMessage()    {}
func (*SProductModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{6}
}
func (m *SProductModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductModel.Unmarshal(m, b)
}
func (m *SProductModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductModel.Marshal(b, m, deterministic)
}
func (dst *SProductModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductModel.Merge(dst, src)
}
func (m *SProductModel) XXX_Size() int {
	return xxx_messageInfo_SProductModel.Size(m)
}
func (m *SProductModel) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductModel.DiscardUnknown(m)
}

var xxx_messageInfo_SProductModel proto.InternalMessageInfo

func (m *SProductModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SProductModel) GetAttrStr() string {
	if m != nil {
		return m.AttrStr
	}
	return ""
}

func (m *SProductModel) GetSpecStr() string {
	if m != nil {
		return m.SpecStr
	}
	return ""
}

func (m *SProductModel) GetAttrs() []*SProductAttr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *SProductModel) GetSpecs() []*SProductSpec {
	if m != nil {
		return m.Specs
	}
	return nil
}

func (m *SProductModel) GetBrands() []*SProductBrand {
	if m != nil {
		return m.Brands
	}
	return nil
}

func (m *SProductModel) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

// 产品模型属性
type SProductAttr struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 属性名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	// 是否作为筛选条件
	IsFilter int32 `protobuf:"varint,3,opt,name=IsFilter,proto3" json:"IsFilter"`
	// 是否多选
	MultiCheck int32 `protobuf:"varint,4,opt,name=MultiCheck,proto3" json:"MultiCheck"`
	// 排列序号
	SortNum int32 `protobuf:"varint,5,opt,name=SortNum,proto3" json:"SortNum"`
	// 属性项值
	ItemValues string `protobuf:"bytes,6,opt,name=ItemValues,proto3" json:"ItemValues"`
	// 属性项
	Items                []*SProductAttrItem `protobuf:"bytes,7,rep,name=Items,proto3" json:"Items"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SProductAttr) Reset()         { *m = SProductAttr{} }
func (m *SProductAttr) String() string { return proto.CompactTextString(m) }
func (*SProductAttr) ProtoMessage()    {}
func (*SProductAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{7}
}
func (m *SProductAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductAttr.Unmarshal(m, b)
}
func (m *SProductAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductAttr.Marshal(b, m, deterministic)
}
func (dst *SProductAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductAttr.Merge(dst, src)
}
func (m *SProductAttr) XXX_Size() int {
	return xxx_messageInfo_SProductAttr.Size(m)
}
func (m *SProductAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductAttr.DiscardUnknown(m)
}

var xxx_messageInfo_SProductAttr proto.InternalMessageInfo

func (m *SProductAttr) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductAttr) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SProductAttr) GetIsFilter() int32 {
	if m != nil {
		return m.IsFilter
	}
	return 0
}

func (m *SProductAttr) GetMultiCheck() int32 {
	if m != nil {
		return m.MultiCheck
	}
	return 0
}

func (m *SProductAttr) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

func (m *SProductAttr) GetItemValues() string {
	if m != nil {
		return m.ItemValues
	}
	return ""
}

func (m *SProductAttr) GetItems() []*SProductAttrItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 产品模型属性项
type SProductAttrItem struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 属性值
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value"`
	// 排列序号
	SortNum              int32    `protobuf:"varint,3,opt,name=SortNum,proto3" json:"SortNum"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SProductAttrItem) Reset()         { *m = SProductAttrItem{} }
func (m *SProductAttrItem) String() string { return proto.CompactTextString(m) }
func (*SProductAttrItem) ProtoMessage()    {}
func (*SProductAttrItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{8}
}
func (m *SProductAttrItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductAttrItem.Unmarshal(m, b)
}
func (m *SProductAttrItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductAttrItem.Marshal(b, m, deterministic)
}
func (dst *SProductAttrItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductAttrItem.Merge(dst, src)
}
func (m *SProductAttrItem) XXX_Size() int {
	return xxx_messageInfo_SProductAttrItem.Size(m)
}
func (m *SProductAttrItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductAttrItem.DiscardUnknown(m)
}

var xxx_messageInfo_SProductAttrItem proto.InternalMessageInfo

func (m *SProductAttrItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductAttrItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SProductAttrItem) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

// 产品属性值
type SProductAttrValue struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 属性编号
	AttrId int64 `protobuf:"varint,2,opt,name=AttrId,proto3" json:"AttrId"`
	// 属性名称
	AttrName string `protobuf:"bytes,3,opt,name=AttrName,proto3" json:"AttrName"`
	// 属性值
	AttrData string `protobuf:"bytes,4,opt,name=AttrData,proto3" json:"AttrData"`
	// 属性文本
	AttrWord             string   `protobuf:"bytes,5,opt,name=AttrWord,proto3" json:"AttrWord"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SProductAttrValue) Reset()         { *m = SProductAttrValue{} }
func (m *SProductAttrValue) String() string { return proto.CompactTextString(m) }
func (*SProductAttrValue) ProtoMessage()    {}
func (*SProductAttrValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{9}
}
func (m *SProductAttrValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductAttrValue.Unmarshal(m, b)
}
func (m *SProductAttrValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductAttrValue.Marshal(b, m, deterministic)
}
func (dst *SProductAttrValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductAttrValue.Merge(dst, src)
}
func (m *SProductAttrValue) XXX_Size() int {
	return xxx_messageInfo_SProductAttrValue.Size(m)
}
func (m *SProductAttrValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductAttrValue.DiscardUnknown(m)
}

var xxx_messageInfo_SProductAttrValue proto.InternalMessageInfo

func (m *SProductAttrValue) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductAttrValue) GetAttrId() int64 {
	if m != nil {
		return m.AttrId
	}
	return 0
}

func (m *SProductAttrValue) GetAttrName() string {
	if m != nil {
		return m.AttrName
	}
	return ""
}

func (m *SProductAttrValue) GetAttrData() string {
	if m != nil {
		return m.AttrData
	}
	return ""
}

func (m *SProductAttrValue) GetAttrWord() string {
	if m != nil {
		return m.AttrWord
	}
	return ""
}

// 产品模型规格
type SProductSpec struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 规格名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	// 排列序号
	SortNum int32 `protobuf:"varint,3,opt,name=SortNum,proto3" json:"SortNum"`
	// 规格项值
	ItemValues string `protobuf:"bytes,4,opt,name=ItemValues,proto3" json:"ItemValues"`
	// 规格项
	Items                []*SProductSpecItem `protobuf:"bytes,5,rep,name=Items,proto3" json:"Items"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SProductSpec) Reset()         { *m = SProductSpec{} }
func (m *SProductSpec) String() string { return proto.CompactTextString(m) }
func (*SProductSpec) ProtoMessage()    {}
func (*SProductSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{10}
}
func (m *SProductSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductSpec.Unmarshal(m, b)
}
func (m *SProductSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductSpec.Marshal(b, m, deterministic)
}
func (dst *SProductSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductSpec.Merge(dst, src)
}
func (m *SProductSpec) XXX_Size() int {
	return xxx_messageInfo_SProductSpec.Size(m)
}
func (m *SProductSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SProductSpec proto.InternalMessageInfo

func (m *SProductSpec) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SProductSpec) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

func (m *SProductSpec) GetItemValues() string {
	if m != nil {
		return m.ItemValues
	}
	return ""
}

func (m *SProductSpec) GetItems() []*SProductSpecItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 规格项
type SProductSpecItem struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 规格项值
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value"`
	// 规格项颜色
	Color string `protobuf:"bytes,3,opt,name=Color,proto3" json:"Color"`
	// 排列序号
	SortNum              int32    `protobuf:"varint,4,opt,name=SortNum,proto3" json:"SortNum"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SProductSpecItem) Reset()         { *m = SProductSpecItem{} }
func (m *SProductSpecItem) String() string { return proto.CompactTextString(m) }
func (*SProductSpecItem) ProtoMessage()    {}
func (*SProductSpecItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{11}
}
func (m *SProductSpecItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductSpecItem.Unmarshal(m, b)
}
func (m *SProductSpecItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductSpecItem.Marshal(b, m, deterministic)
}
func (dst *SProductSpecItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductSpecItem.Merge(dst, src)
}
func (m *SProductSpecItem) XXX_Size() int {
	return xxx_messageInfo_SProductSpecItem.Size(m)
}
func (m *SProductSpecItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductSpecItem.DiscardUnknown(m)
}

var xxx_messageInfo_SProductSpecItem proto.InternalMessageInfo

func (m *SProductSpecItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductSpecItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SProductSpecItem) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *SProductSpecItem) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

type ProductBrandListResponse struct {
	Value                []*SProductBrand `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProductBrandListResponse) Reset()         { *m = ProductBrandListResponse{} }
func (m *ProductBrandListResponse) String() string { return proto.CompactTextString(m) }
func (*ProductBrandListResponse) ProtoMessage()    {}
func (*ProductBrandListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{12}
}
func (m *ProductBrandListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductBrandListResponse.Unmarshal(m, b)
}
func (m *ProductBrandListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductBrandListResponse.Marshal(b, m, deterministic)
}
func (dst *ProductBrandListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductBrandListResponse.Merge(dst, src)
}
func (m *ProductBrandListResponse) XXX_Size() int {
	return xxx_messageInfo_ProductBrandListResponse.Size(m)
}
func (m *ProductBrandListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductBrandListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductBrandListResponse proto.InternalMessageInfo

func (m *ProductBrandListResponse) GetValue() []*SProductBrand {
	if m != nil {
		return m.Value
	}
	return nil
}

// 品牌
type SProductBrand struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 品牌名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	// 品牌图片
	Image string `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image"`
	// 品牌网址
	SiteUrl string `protobuf:"bytes,4,opt,name=SiteUrl,proto3" json:"SiteUrl"`
	// 介绍
	Introduce string `protobuf:"bytes,5,opt,name=Introduce,proto3" json:"Introduce"`
	// 是否审核
	ReviewState int32 `protobuf:"varint,6,opt,name=ReviewState,proto3" json:"ReviewState"`
	// 审核意见
	ReviewRemark string `protobuf:"bytes,7,opt,name=ReviewRemark,proto3" json:"ReviewRemark"`
	// 是否启用
	Enabled int32 `protobuf:"varint,8,opt,name=Enabled,proto3" json:"Enabled"`
	// 加入时间
	CreateTime           int64    `protobuf:"varint,9,opt,name=CreateTime,proto3" json:"CreateTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SProductBrand) Reset()         { *m = SProductBrand{} }
func (m *SProductBrand) String() string { return proto.CompactTextString(m) }
func (*SProductBrand) ProtoMessage()    {}
func (*SProductBrand) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{13}
}
func (m *SProductBrand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductBrand.Unmarshal(m, b)
}
func (m *SProductBrand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductBrand.Marshal(b, m, deterministic)
}
func (dst *SProductBrand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductBrand.Merge(dst, src)
}
func (m *SProductBrand) XXX_Size() int {
	return xxx_messageInfo_SProductBrand.Size(m)
}
func (m *SProductBrand) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductBrand.DiscardUnknown(m)
}

var xxx_messageInfo_SProductBrand proto.InternalMessageInfo

func (m *SProductBrand) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductBrand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SProductBrand) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *SProductBrand) GetSiteUrl() string {
	if m != nil {
		return m.SiteUrl
	}
	return ""
}

func (m *SProductBrand) GetIntroduce() string {
	if m != nil {
		return m.Introduce
	}
	return ""
}

func (m *SProductBrand) GetReviewState() int32 {
	if m != nil {
		return m.ReviewState
	}
	return 0
}

func (m *SProductBrand) GetReviewRemark() string {
	if m != nil {
		return m.ReviewRemark
	}
	return ""
}

func (m *SProductBrand) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *SProductBrand) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type ProductCategoriesResponse struct {
	Value                []*SProductCategory `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProductCategoriesResponse) Reset()         { *m = ProductCategoriesResponse{} }
func (m *ProductCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ProductCategoriesResponse) ProtoMessage()    {}
func (*ProductCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{14}
}
func (m *ProductCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCategoriesResponse.Unmarshal(m, b)
}
func (m *ProductCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCategoriesResponse.Marshal(b, m, deterministic)
}
func (dst *ProductCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCategoriesResponse.Merge(dst, src)
}
func (m *ProductCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_ProductCategoriesResponse.Size(m)
}
func (m *ProductCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCategoriesResponse proto.InternalMessageInfo

func (m *ProductCategoriesResponse) GetValue() []*SProductCategory {
	if m != nil {
		return m.Value
	}
	return nil
}

type CategoryParentId struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryParentId) Reset()         { *m = CategoryParentId{} }
func (m *CategoryParentId) String() string { return proto.CompactTextString(m) }
func (*CategoryParentId) ProtoMessage()    {}
func (*CategoryParentId) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{15}
}
func (m *CategoryParentId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryParentId.Unmarshal(m, b)
}
func (m *CategoryParentId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryParentId.Marshal(b, m, deterministic)
}
func (dst *CategoryParentId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryParentId.Merge(dst, src)
}
func (m *CategoryParentId) XXX_Size() int {
	return xxx_messageInfo_CategoryParentId.Size(m)
}
func (m *CategoryParentId) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryParentId.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryParentId proto.InternalMessageInfo

func (m *CategoryParentId) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 商品分类
type SProductCategory struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 上级分类
	ParentId int64 `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId"`
	// 产品模型
	ModelId int64 `protobuf:"varint,3,opt,name=ModelId,proto3" json:"ModelId"`
	// 优先级
	Priority int32 `protobuf:"varint,4,opt,name=Priority,proto3" json:"Priority"`
	// 分类名称
	Name string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name"`
	// * 是否为虚拟分类
	IsVirtual bool `protobuf:"varint,6,opt,name=IsVirtual,proto3" json:"IsVirtual"`
	// * 分类链接地址
	CategoryUrl string `protobuf:"bytes,7,opt,name=CategoryUrl,proto3" json:"CategoryUrl"`
	// 虚拟分类跳转地址
	RedirectUrl string `protobuf:"bytes,18,opt,name=RedirectUrl,proto3" json:"RedirectUrl"`
	// * 图标
	Icon string `protobuf:"bytes,8,opt,name=Icon,proto3" json:"Icon"`
	// * 图标坐标
	IconPoint string `protobuf:"bytes,9,opt,name=IconPoint,proto3" json:"IconPoint"`
	// * 分类层级
	Level int32 `protobuf:"varint,10,opt,name=Level,proto3" json:"Level"`
	// * 序号
	SortNum int32 `protobuf:"varint,11,opt,name=SortNum,proto3" json:"SortNum"`
	// * 是否楼层显示
	FloorShow bool `protobuf:"varint,12,opt,name=FloorShow,proto3" json:"FloorShow"`
	// * 是否启用
	Enabled bool `protobuf:"varint,13,opt,name=Enabled,proto3" json:"Enabled"`
	// * 创建时间
	CreateTime int64 `protobuf:"varint,14,opt,name=CreateTime,proto3" json:"CreateTime"`
	// 选项参数
	Options map[string]string `protobuf:"bytes,15,rep,name=Options,proto3" json:"Options" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 关联品牌
	Brands []*SProductBrand `protobuf:"bytes,16,rep,name=Brands,proto3" json:"Brands"`
	// * 子分类
	Children             []*SProductCategory `protobuf:"bytes,17,rep,name=Children,proto3" json:"Children"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SProductCategory) Reset()         { *m = SProductCategory{} }
func (m *SProductCategory) String() string { return proto.CompactTextString(m) }
func (*SProductCategory) ProtoMessage()    {}
func (*SProductCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{16}
}
func (m *SProductCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProductCategory.Unmarshal(m, b)
}
func (m *SProductCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProductCategory.Marshal(b, m, deterministic)
}
func (dst *SProductCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProductCategory.Merge(dst, src)
}
func (m *SProductCategory) XXX_Size() int {
	return xxx_messageInfo_SProductCategory.Size(m)
}
func (m *SProductCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_SProductCategory.DiscardUnknown(m)
}

var xxx_messageInfo_SProductCategory proto.InternalMessageInfo

func (m *SProductCategory) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProductCategory) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *SProductCategory) GetModelId() int64 {
	if m != nil {
		return m.ModelId
	}
	return 0
}

func (m *SProductCategory) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *SProductCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SProductCategory) GetIsVirtual() bool {
	if m != nil {
		return m.IsVirtual
	}
	return false
}

func (m *SProductCategory) GetCategoryUrl() string {
	if m != nil {
		return m.CategoryUrl
	}
	return ""
}

func (m *SProductCategory) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

func (m *SProductCategory) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SProductCategory) GetIconPoint() string {
	if m != nil {
		return m.IconPoint
	}
	return ""
}

func (m *SProductCategory) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *SProductCategory) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

func (m *SProductCategory) GetFloorShow() bool {
	if m != nil {
		return m.FloorShow
	}
	return false
}

func (m *SProductCategory) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *SProductCategory) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SProductCategory) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SProductCategory) GetBrands() []*SProductBrand {
	if m != nil {
		return m.Brands
	}
	return nil
}

func (m *SProductCategory) GetChildren() []*SProductCategory {
	if m != nil {
		return m.Children
	}
	return nil
}

// 保存分类请求
type SaveProductCategoryRequest struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 上级分类
	ParentId int64 `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId"`
	// 产品模型
	ModelId int64 `protobuf:"varint,3,opt,name=ModelId,proto3" json:"ModelId"`
	// 优先级
	Priority int32 `protobuf:"varint,4,opt,name=Priority,proto3" json:"Priority"`
	// 分类名称
	Name string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name"`
	// * 是否为虚拟分类
	IsVirtual bool `protobuf:"varint,6,opt,name=IsVirtual,proto3" json:"IsVirtual"`
	// * 分类链接地址
	CategoryUrl string `protobuf:"bytes,7,opt,name=CategoryUrl,proto3" json:"CategoryUrl"`
	// 虚拟分类跳转地址
	RedirectUrl string `protobuf:"bytes,18,opt,name=RedirectUrl,proto3" json:"RedirectUrl"`
	// * 图标
	Icon string `protobuf:"bytes,8,opt,name=Icon,proto3" json:"Icon"`
	// * 图标坐标
	IconPoint string `protobuf:"bytes,9,opt,name=IconPoint,proto3" json:"IconPoint"`
	// * 序号
	SortNum int32 `protobuf:"varint,11,opt,name=SortNum,proto3" json:"SortNum"`
	// * 是否楼层显示
	FloorShow bool `protobuf:"varint,12,opt,name=FloorShow,proto3" json:"FloorShow"`
	// * 是否启用
	Enabled              bool     `protobuf:"varint,13,opt,name=Enabled,proto3" json:"Enabled"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveProductCategoryRequest) Reset()         { *m = SaveProductCategoryRequest{} }
func (m *SaveProductCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*SaveProductCategoryRequest) ProtoMessage()    {}
func (*SaveProductCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{17}
}
func (m *SaveProductCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveProductCategoryRequest.Unmarshal(m, b)
}
func (m *SaveProductCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveProductCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *SaveProductCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveProductCategoryRequest.Merge(dst, src)
}
func (m *SaveProductCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_SaveProductCategoryRequest.Size(m)
}
func (m *SaveProductCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveProductCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveProductCategoryRequest proto.InternalMessageInfo

func (m *SaveProductCategoryRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaveProductCategoryRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *SaveProductCategoryRequest) GetModelId() int64 {
	if m != nil {
		return m.ModelId
	}
	return 0
}

func (m *SaveProductCategoryRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *SaveProductCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveProductCategoryRequest) GetIsVirtual() bool {
	if m != nil {
		return m.IsVirtual
	}
	return false
}

func (m *SaveProductCategoryRequest) GetCategoryUrl() string {
	if m != nil {
		return m.CategoryUrl
	}
	return ""
}

func (m *SaveProductCategoryRequest) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

func (m *SaveProductCategoryRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SaveProductCategoryRequest) GetIconPoint() string {
	if m != nil {
		return m.IconPoint
	}
	return ""
}

func (m *SaveProductCategoryRequest) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

func (m *SaveProductCategoryRequest) GetFloorShow() bool {
	if m != nil {
		return m.FloorShow
	}
	return false
}

func (m *SaveProductCategoryRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// 保存分类响应
type SaveProductCategoryResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error"`
	CategoryId           int64    `protobuf:"varint,2,opt,name=CategoryId,proto3" json:"CategoryId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveProductCategoryResponse) Reset()         { *m = SaveProductCategoryResponse{} }
func (m *SaveProductCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*SaveProductCategoryResponse) ProtoMessage()    {}
func (*SaveProductCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{18}
}
func (m *SaveProductCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveProductCategoryResponse.Unmarshal(m, b)
}
func (m *SaveProductCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveProductCategoryResponse.Marshal(b, m, deterministic)
}
func (dst *SaveProductCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveProductCategoryResponse.Merge(dst, src)
}
func (m *SaveProductCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_SaveProductCategoryResponse.Size(m)
}
func (m *SaveProductCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveProductCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveProductCategoryResponse proto.InternalMessageInfo

func (m *SaveProductCategoryResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SaveProductCategoryResponse) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

// 分类树形请求
type CategoryTreeRequest struct {
	// 上级编号
	ParentId int64 `protobuf:"varint,1,opt,name=ParentId,proto3" json:"ParentId"`
	// 排除分类编号
	ExcludeIdList []int64 `protobuf:"varint,2,rep,packed,name=ExcludeIdList,proto3" json:"ExcludeIdList"`
	// 层级显示,小于等于0不限制
	Depth int32 `protobuf:"varint,3,opt,name=Depth,proto3" json:"Depth"`
	// 初始化数据ID
	InitialId            int64    `protobuf:"varint,4,opt,name=InitialId,proto3" json:"InitialId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryTreeRequest) Reset()         { *m = CategoryTreeRequest{} }
func (m *CategoryTreeRequest) String() string { return proto.CompactTextString(m) }
func (*CategoryTreeRequest) ProtoMessage()    {}
func (*CategoryTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{19}
}
func (m *CategoryTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryTreeRequest.Unmarshal(m, b)
}
func (m *CategoryTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryTreeRequest.Marshal(b, m, deterministic)
}
func (dst *CategoryTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryTreeRequest.Merge(dst, src)
}
func (m *CategoryTreeRequest) XXX_Size() int {
	return xxx_messageInfo_CategoryTreeRequest.Size(m)
}
func (m *CategoryTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryTreeRequest proto.InternalMessageInfo

func (m *CategoryTreeRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CategoryTreeRequest) GetExcludeIdList() []int64 {
	if m != nil {
		return m.ExcludeIdList
	}
	return nil
}

func (m *CategoryTreeRequest) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *CategoryTreeRequest) GetInitialId() int64 {
	if m != nil {
		return m.InitialId
	}
	return 0
}

// 分类树形结果
type CategoryTreeResponse struct {
	Value []*STreeNode `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value"`
	// 返回初始化上级ID列表
	InitialList          []int64  `protobuf:"varint,2,rep,packed,name=InitialList,proto3" json:"InitialList"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryTreeResponse) Reset()         { *m = CategoryTreeResponse{} }
func (m *CategoryTreeResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryTreeResponse) ProtoMessage()    {}
func (*CategoryTreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{20}
}
func (m *CategoryTreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryTreeResponse.Unmarshal(m, b)
}
func (m *CategoryTreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryTreeResponse.Marshal(b, m, deterministic)
}
func (dst *CategoryTreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryTreeResponse.Merge(dst, src)
}
func (m *CategoryTreeResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryTreeResponse.Size(m)
}
func (m *CategoryTreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryTreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryTreeResponse proto.InternalMessageInfo

func (m *CategoryTreeResponse) GetValue() []*STreeNode {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CategoryTreeResponse) GetInitialList() []int64 {
	if m != nil {
		return m.InitialList
	}
	return nil
}

// 产品
type SProduct struct {
	// 编号
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// 分类
	CategoryId int64 `protobuf:"varint,2,opt,name=CategoryId,proto3" json:"CategoryId"`
	// 名称
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name"`
	// 供应商编号(暂时同mch_id)
	VendorId int64 `protobuf:"varint,4,opt,name=VendorId,proto3" json:"VendorId"`
	// 品牌编号
	BrandId int64 `protobuf:"varint,5,opt,name=BrandId,proto3" json:"BrandId"`
	// 商家编码
	Code string `protobuf:"bytes,6,opt,name=Code,proto3" json:"Code"`
	// 图片
	Image string `protobuf:"bytes,7,opt,name=Image,proto3" json:"Image"`
	// 描述
	Description string `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description"`
	// 备注
	Remark string `protobuf:"bytes,9,opt,name=Remark,proto3" json:"Remark"`
	// 状态
	State int32 `protobuf:"varint,10,opt,name=State,proto3" json:"State"`
	// 排序编号
	SortNum int32 `protobuf:"varint,11,opt,name=SortNum,proto3" json:"SortNum"`
	// 产品属性
	Attrs []*SProductAttrValue `protobuf:"bytes,12,rep,name=Attrs,proto3" json:"Attrs"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,13,opt,name=CreateTime,proto3" json:"CreateTime"`
	// 更新时间
	UpdateTime           int64    `protobuf:"varint,14,opt,name=UpdateTime,proto3" json:"UpdateTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SProduct) Reset()         { *m = SProduct{} }
func (m *SProduct) String() string { return proto.CompactTextString(m) }
func (*SProduct) ProtoMessage()    {}
func (*SProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{21}
}
func (m *SProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SProduct.Unmarshal(m, b)
}
func (m *SProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SProduct.Marshal(b, m, deterministic)
}
func (dst *SProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SProduct.Merge(dst, src)
}
func (m *SProduct) XXX_Size() int {
	return xxx_messageInfo_SProduct.Size(m)
}
func (m *SProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_SProduct.DiscardUnknown(m)
}

var xxx_messageInfo_SProduct proto.InternalMessageInfo

func (m *SProduct) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SProduct) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *SProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SProduct) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *SProduct) GetBrandId() int64 {
	if m != nil {
		return m.BrandId
	}
	return 0
}

func (m *SProduct) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SProduct) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *SProduct) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SProduct) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *SProduct) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *SProduct) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

func (m *SProduct) GetAttrs() []*SProductAttrValue {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *SProduct) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SProduct) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type ProductInfoRequest struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=ProductId,proto3" json:"ProductId"`
	Info                 string   `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductInfoRequest) Reset()         { *m = ProductInfoRequest{} }
func (m *ProductInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ProductInfoRequest) ProtoMessage()    {}
func (*ProductInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{22}
}
func (m *ProductInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductInfoRequest.Unmarshal(m, b)
}
func (m *ProductInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductInfoRequest.Marshal(b, m, deterministic)
}
func (dst *ProductInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductInfoRequest.Merge(dst, src)
}
func (m *ProductInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ProductInfoRequest.Size(m)
}
func (m *ProductInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductInfoRequest proto.InternalMessageInfo

func (m *ProductInfoRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *ProductInfoRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type SaveProductResponse struct {
	ErrCode              int64    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg"`
	ProductId            int64    `protobuf:"varint,3,opt,name=ProductId,proto3" json:"ProductId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveProductResponse) Reset()         { *m = SaveProductResponse{} }
func (m *SaveProductResponse) String() string { return proto.CompactTextString(m) }
func (*SaveProductResponse) ProtoMessage()    {}
func (*SaveProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_service_8c7e9ec9bd0c9531, []int{23}
}
func (m *SaveProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveProductResponse.Unmarshal(m, b)
}
func (m *SaveProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveProductResponse.Marshal(b, m, deterministic)
}
func (dst *SaveProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveProductResponse.Merge(dst, src)
}
func (m *SaveProductResponse) XXX_Size() int {
	return xxx_messageInfo_SaveProductResponse.Size(m)
}
func (m *SaveProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveProductResponse proto.InternalMessageInfo

func (m *SaveProductResponse) GetErrCode() int64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *SaveProductResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *SaveProductResponse) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteProductRequest)(nil), "DeleteProductRequest")
	proto.RegisterType((*ProductId)(nil), "ProductId")
	proto.RegisterType((*ProductModelId)(nil), "ProductModelId")
	proto.RegisterType((*ProductAttrId)(nil), "ProductAttrId")
	proto.RegisterType((*ProductAttrItemId)(nil), "ProductAttrItemId")
	proto.RegisterType((*ProductModelListResponse)(nil), "ProductModelListResponse")
	proto.RegisterType((*SProductModel)(nil), "SProductModel")
	proto.RegisterType((*SProductAttr)(nil), "SProductAttr")
	proto.RegisterType((*SProductAttrItem)(nil), "SProductAttrItem")
	proto.RegisterType((*SProductAttrValue)(nil), "SProductAttrValue")
	proto.RegisterType((*SProductSpec)(nil), "SProductSpec")
	proto.RegisterType((*SProductSpecItem)(nil), "SProductSpecItem")
	proto.RegisterType((*ProductBrandListResponse)(nil), "ProductBrandListResponse")
	proto.RegisterType((*SProductBrand)(nil), "SProductBrand")
	proto.RegisterType((*ProductCategoriesResponse)(nil), "ProductCategoriesResponse")
	proto.RegisterType((*CategoryParentId)(nil), "CategoryParentId")
	proto.RegisterType((*SProductCategory)(nil), "SProductCategory")
	proto.RegisterMapType((map[string]string)(nil), "SProductCategory.OptionsEntry")
	proto.RegisterType((*SaveProductCategoryRequest)(nil), "SaveProductCategoryRequest")
	proto.RegisterType((*SaveProductCategoryResponse)(nil), "SaveProductCategoryResponse")
	proto.RegisterType((*CategoryTreeRequest)(nil), "CategoryTreeRequest")
	proto.RegisterType((*CategoryTreeResponse)(nil), "CategoryTreeResponse")
	proto.RegisterType((*SProduct)(nil), "SProduct")
	proto.RegisterType((*ProductInfoRequest)(nil), "ProductInfoRequest")
	proto.RegisterType((*SaveProductResponse)(nil), "SaveProductResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	// 获取产品模型
	GetModel(ctx context.Context, in *ProductModelId, opts ...grpc.CallOption) (*SProductModel, error)
	// 获取产品模型
	GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductModelListResponse, error)
	// 获取属性
	GetAttr(ctx context.Context, in *ProductAttrId, opts ...grpc.CallOption) (*SProductAttr, error)
	// 获取属性项
	GetAttrItem(ctx context.Context, in *ProductAttrItemId, opts ...grpc.CallOption) (*SProductAttrItem, error)
	// 获取模型属性Html
	GetModelAttrsHtml(ctx context.Context, in *ProductModelId, opts ...grpc.CallOption) (*String, error)
	// 保存产品模型
	SaveModel(ctx context.Context, in *SProductModel, opts ...grpc.CallOption) (*Result, error)
	// 删除产品模型
	DeleteModel_(ctx context.Context, in *ProductModelId, opts ...grpc.CallOption) (*Result, error)
	// Get 产品品牌
	GetBrand(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*SProductBrand, error)
	// Save 产品品牌
	SaveBrand(ctx context.Context, in *SProductBrand, opts ...grpc.CallOption) (*Result, error)
	// Delete 产品品牌
	DeleteBrand(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error)
	// 获取所有产品品牌
	GetBrands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductBrandListResponse, error)
	// 获取全部分类
	GetCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductCategoriesResponse, error)
	// 获取商品分类
	GetCategory(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*SProductCategory, error)
	// 获取商品分类和选项
	//    rpc GetCategoryAndOptions(mchId int64, id int32) (*product.Category,
	//    domain.IOptionStore)
	DeleteCategory(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error)
	// 保存产品分类
	SaveCategory(ctx context.Context, in *SaveProductCategoryRequest, opts ...grpc.CallOption) (*SaveProductCategoryResponse, error)
	// 获取分类树形数据
	GetCategoryTreeNode(ctx context.Context, in *CategoryTreeRequest, opts ...grpc.CallOption) (*CategoryTreeResponse, error)
	// 根据上级编号获取分类列表
	GetChildren(ctx context.Context, in *CategoryParentId, opts ...grpc.CallOption) (*ProductCategoriesResponse, error)
	// 获取产品值
	GetProduct(ctx context.Context, in *ProductId, opts ...grpc.CallOption) (*SProduct, error)
	// 保存产品
	SaveProduct(ctx context.Context, in *SProduct, opts ...grpc.CallOption) (*SaveProductResponse, error)
	// 删除产品
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*Result, error)
	// 保存货品描述
	SaveProductInfo(ctx context.Context, in *ProductInfoRequest, opts ...grpc.CallOption) (*Result, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetModel(ctx context.Context, in *ProductModelId, opts ...grpc.CallOption) (*SProductModel, error) {
	out := new(SProductModel)
	err := c.cc.Invoke(ctx, "/ProductService/GetModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductModelListResponse, error) {
	out := new(ProductModelListResponse)
	err := c.cc.Invoke(ctx, "/ProductService/GetModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetAttr(ctx context.Context, in *ProductAttrId, opts ...grpc.CallOption) (*SProductAttr, error) {
	out := new(SProductAttr)
	err := c.cc.Invoke(ctx, "/ProductService/GetAttr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetAttrItem(ctx context.Context, in *ProductAttrItemId, opts ...grpc.CallOption) (*SProductAttrItem, error) {
	out := new(SProductAttrItem)
	err := c.cc.Invoke(ctx, "/ProductService/GetAttrItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetModelAttrsHtml(ctx context.Context, in *ProductModelId, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/ProductService/GetModelAttrsHtml", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveModel(ctx context.Context, in *SProductModel, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProductService/SaveModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteModel_(ctx context.Context, in *ProductModelId, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProductService/DeleteModel_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetBrand(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*SProductBrand, error) {
	out := new(SProductBrand)
	err := c.cc.Invoke(ctx, "/ProductService/GetBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveBrand(ctx context.Context, in *SProductBrand, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProductService/SaveBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteBrand(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProductService/DeleteBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetBrands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductBrandListResponse, error) {
	out := new(ProductBrandListResponse)
	err := c.cc.Invoke(ctx, "/ProductService/GetBrands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductCategoriesResponse, error) {
	out := new(ProductCategoriesResponse)
	err := c.cc.Invoke(ctx, "/ProductService/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetCategory(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*SProductCategory, error) {
	out := new(SProductCategory)
	err := c.cc.Invoke(ctx, "/ProductService/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteCategory(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProductService/DeleteCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveCategory(ctx context.Context, in *SaveProductCategoryRequest, opts ...grpc.CallOption) (*SaveProductCategoryResponse, error) {
	out := new(SaveProductCategoryResponse)
	err := c.cc.Invoke(ctx, "/ProductService/SaveCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetCategoryTreeNode(ctx context.Context, in *CategoryTreeRequest, opts ...grpc.CallOption) (*CategoryTreeResponse, error) {
	out := new(CategoryTreeResponse)
	err := c.cc.Invoke(ctx, "/ProductService/GetCategoryTreeNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetChildren(ctx context.Context, in *CategoryParentId, opts ...grpc.CallOption) (*ProductCategoriesResponse, error) {
	out := new(ProductCategoriesResponse)
	err := c.cc.Invoke(ctx, "/ProductService/GetChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *ProductId, opts ...grpc.CallOption) (*SProduct, error) {
	out := new(SProduct)
	err := c.cc.Invoke(ctx, "/ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveProduct(ctx context.Context, in *SProduct, opts ...grpc.CallOption) (*SaveProductResponse, error) {
	out := new(SaveProductResponse)
	err := c.cc.Invoke(ctx, "/ProductService/SaveProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveProductInfo(ctx context.Context, in *ProductInfoRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProductService/SaveProductInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	// 获取产品模型
	GetModel(context.Context, *ProductModelId) (*SProductModel, error)
	// 获取产品模型
	GetModels(context.Context, *Empty) (*ProductModelListResponse, error)
	// 获取属性
	GetAttr(context.Context, *ProductAttrId) (*SProductAttr, error)
	// 获取属性项
	GetAttrItem(context.Context, *ProductAttrItemId) (*SProductAttrItem, error)
	// 获取模型属性Html
	GetModelAttrsHtml(context.Context, *ProductModelId) (*String, error)
	// 保存产品模型
	SaveModel(context.Context, *SProductModel) (*Result, error)
	// 删除产品模型
	DeleteModel_(context.Context, *ProductModelId) (*Result, error)
	// Get 产品品牌
	GetBrand(context.Context, *Int64) (*SProductBrand, error)
	// Save 产品品牌
	SaveBrand(context.Context, *SProductBrand) (*Result, error)
	// Delete 产品品牌
	DeleteBrand(context.Context, *Int64) (*Result, error)
	// 获取所有产品品牌
	GetBrands(context.Context, *Empty) (*ProductBrandListResponse, error)
	// 获取全部分类
	GetCategories(context.Context, *Empty) (*ProductCategoriesResponse, error)
	// 获取商品分类
	GetCategory(context.Context, *Int64) (*SProductCategory, error)
	// 获取商品分类和选项
	//    rpc GetCategoryAndOptions(mchId int64, id int32) (*product.Category,
	//    domain.IOptionStore)
	DeleteCategory(context.Context, *Int64) (*Result, error)
	// 保存产品分类
	SaveCategory(context.Context, *SaveProductCategoryRequest) (*SaveProductCategoryResponse, error)
	// 获取分类树形数据
	GetCategoryTreeNode(context.Context, *CategoryTreeRequest) (*CategoryTreeResponse, error)
	// 根据上级编号获取分类列表
	GetChildren(context.Context, *CategoryParentId) (*ProductCategoriesResponse, error)
	// 获取产品值
	GetProduct(context.Context, *ProductId) (*SProduct, error)
	// 保存产品
	SaveProduct(context.Context, *SProduct) (*SaveProductResponse, error)
	// 删除产品
	DeleteProduct(context.Context, *DeleteProductRequest) (*Result, error)
	// 保存货品描述
	SaveProductInfo(context.Context, *ProductInfoRequest) (*Result, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductModelId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetModel(ctx, req.(*ProductModelId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductAttrId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetAttr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetAttr(ctx, req.(*ProductAttrId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetAttrItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductAttrItemId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetAttrItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetAttrItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetAttrItem(ctx, req.(*ProductAttrItemId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetModelAttrsHtml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductModelId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetModelAttrsHtml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetModelAttrsHtml",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetModelAttrsHtml(ctx, req.(*ProductModelId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SProductModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/SaveModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveModel(ctx, req.(*SProductModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteModel__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductModelId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteModel_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/DeleteModel_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteModel_(ctx, req.(*ProductModelId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetBrand(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SProductBrand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/SaveBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveBrand(ctx, req.(*SProductBrand))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/DeleteBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteBrand(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetBrands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetBrands(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetCategories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetCategory(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/DeleteCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteCategory(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProductCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/SaveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveCategory(ctx, req.(*SaveProductCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetCategoryTreeNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetCategoryTreeNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetCategoryTreeNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetCategoryTreeNode(ctx, req.(*CategoryTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryParentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetChildren(ctx, req.(*CategoryParentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*ProductId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/SaveProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveProduct(ctx, req.(*SProduct))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveProductInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveProductInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductService/SaveProductInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveProductInfo(ctx, req.(*ProductInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModel",
			Handler:    _ProductService_GetModel_Handler,
		},
		{
			MethodName: "GetModels",
			Handler:    _ProductService_GetModels_Handler,
		},
		{
			MethodName: "GetAttr",
			Handler:    _ProductService_GetAttr_Handler,
		},
		{
			MethodName: "GetAttrItem",
			Handler:    _ProductService_GetAttrItem_Handler,
		},
		{
			MethodName: "GetModelAttrsHtml",
			Handler:    _ProductService_GetModelAttrsHtml_Handler,
		},
		{
			MethodName: "SaveModel",
			Handler:    _ProductService_SaveModel_Handler,
		},
		{
			MethodName: "DeleteModel_",
			Handler:    _ProductService_DeleteModel__Handler,
		},
		{
			MethodName: "GetBrand",
			Handler:    _ProductService_GetBrand_Handler,
		},
		{
			MethodName: "SaveBrand",
			Handler:    _ProductService_SaveBrand_Handler,
		},
		{
			MethodName: "DeleteBrand",
			Handler:    _ProductService_DeleteBrand_Handler,
		},
		{
			MethodName: "GetBrands",
			Handler:    _ProductService_GetBrands_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _ProductService_GetCategories_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ProductService_GetCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _ProductService_DeleteCategory_Handler,
		},
		{
			MethodName: "SaveCategory",
			Handler:    _ProductService_SaveCategory_Handler,
		},
		{
			MethodName: "GetCategoryTreeNode",
			Handler:    _ProductService_GetCategoryTreeNode_Handler,
		},
		{
			MethodName: "GetChildren",
			Handler:    _ProductService_GetChildren_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "SaveProduct",
			Handler:    _ProductService_SaveProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "SaveProductInfo",
			Handler:    _ProductService_SaveProductInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_service.proto",
}

func init() {
	proto.RegisterFile("product_service.proto", fileDescriptor_product_service_8c7e9ec9bd0c9531)
}

var fileDescriptor_product_service_8c7e9ec9bd0c9531 = []byte{
	// 1514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0x97, 0x2c, 0xd3, 0x92, 0x46, 0x92, 0x63, 0xaf, 0x95, 0x3f, 0x18, 0x26, 0xc8, 0x5f, 0x65,
	0x5e, 0x6e, 0x81, 0x32, 0x4d, 0xda, 0x06, 0x41, 0x0a, 0x14, 0x6d, 0x6c, 0xc7, 0x15, 0x9a, 0xa4,
	0x06, 0x95, 0xa4, 0x40, 0x2e, 0x01, 0x2d, 0x6e, 0x64, 0x22, 0x14, 0x57, 0x5d, 0xae, 0x9c, 0xfa,
	0xd8, 0x5e, 0x7b, 0xe8, 0xa9, 0xfd, 0x5e, 0xfd, 0x28, 0x45, 0x2f, 0x3d, 0x16, 0xfb, 0xe4, 0x92,
	0x92, 0x12, 0x1f, 0x7a, 0xec, 0x49, 0x9c, 0xc7, 0xee, 0xce, 0xfc, 0x66, 0x66, 0x67, 0x56, 0x70,
	0x71, 0x46, 0x49, 0x3c, 0x1f, 0xb3, 0x57, 0x39, 0xa6, 0xa7, 0xc9, 0x18, 0x07, 0x33, 0x4a, 0x18,
	0xf1, 0xba, 0x93, 0x94, 0x1c, 0x47, 0xa9, 0xa4, 0xfc, 0x23, 0xe8, 0xef, 0xe3, 0x14, 0x33, 0x7c,
	0x24, 0x95, 0x43, 0xfc, 0xc3, 0x1c, 0xe7, 0x0c, 0x79, 0xd0, 0x1a, 0xe1, 0x34, 0xc5, 0x74, 0x18,
	0xbb, 0xf5, 0x41, 0x7d, 0xb7, 0x11, 0x1a, 0x1a, 0x5d, 0x81, 0xb6, 0xd2, 0x1e, 0xc6, 0xee, 0x9a,
	0x10, 0x16, 0x0c, 0xff, 0x03, 0x4b, 0x8a, 0xfa, 0xe0, 0xbc, 0x88, 0xd2, 0x39, 0x56, 0x7b, 0x48,
	0xc2, 0xbf, 0x09, 0x9b, 0x4a, 0xe5, 0x09, 0x89, 0x71, 0xba, 0x52, 0xef, 0x06, 0xf4, 0x94, 0xde,
	0xd7, 0x8c, 0xd1, 0x95, 0x6a, 0x1f, 0xc2, 0xb6, 0xad, 0xc6, 0xf0, 0x74, 0xa5, 0xea, 0x57, 0xe0,
	0xda, 0x27, 0x3f, 0x4e, 0x72, 0x16, 0xe2, 0x7c, 0x46, 0xb2, 0x1c, 0xa3, 0xeb, 0xc5, 0x8a, 0xc6,
	0x6e, 0xe7, 0xee, 0x66, 0x30, 0xb2, 0x55, 0xf5, 0x0e, 0x7f, 0xd5, 0xa1, 0x57, 0x12, 0xa0, 0x4d,
	0x58, 0x33, 0x20, 0xad, 0x0d, 0x63, 0x84, 0x60, 0xfd, 0x69, 0x34, 0xc5, 0x02, 0x99, 0x76, 0x28,
	0xbe, 0x91, 0x0b, 0x4d, 0x6e, 0xdb, 0x88, 0x51, 0xb7, 0x21, 0xd8, 0x9a, 0xe4, 0x92, 0xd1, 0x0c,
	0x8f, 0xb9, 0x64, 0x5d, 0x4a, 0x14, 0x89, 0xae, 0x81, 0xc3, 0x95, 0x72, 0xd7, 0x11, 0xf6, 0xf4,
	0x8c, 0x3d, 0x9c, 0x1b, 0x4a, 0x19, 0x57, 0xe2, 0xfa, 0xb9, 0xbb, 0x51, 0x51, 0xe2, 0xdc, 0x50,
	0xca, 0xd0, 0x4d, 0xd8, 0x78, 0x48, 0xa3, 0x2c, 0xce, 0xdd, 0x66, 0xc5, 0x35, 0xc1, 0x0e, 0x95,
	0x94, 0xdb, 0x72, 0x90, 0x45, 0xc7, 0x29, 0x8e, 0xdd, 0xd6, 0xa0, 0xbe, 0xeb, 0x84, 0x9a, 0xf4,
	0xff, 0xa8, 0x43, 0xd7, 0x3e, 0xfe, 0x5c, 0x4e, 0x7b, 0xd0, 0x1a, 0xe6, 0x8f, 0x92, 0x94, 0x61,
	0xe9, 0xb5, 0x13, 0x1a, 0x1a, 0x5d, 0x05, 0x78, 0x32, 0x4f, 0x59, 0xb2, 0x77, 0x82, 0xc7, 0x6f,
	0x84, 0xe7, 0x4e, 0x68, 0x71, 0x04, 0x2c, 0x84, 0xb2, 0xa7, 0xf3, 0xa9, 0xeb, 0x48, 0x53, 0x14,
	0xc9, 0x57, 0xf2, 0x10, 0x8b, 0x68, 0x70, 0xb7, 0xf9, 0x79, 0x16, 0x07, 0xdd, 0x02, 0x87, 0x53,
	0xda, 0xd7, 0xed, 0x12, 0x6c, 0x5c, 0x12, 0x4a, 0xb9, 0x1f, 0xc2, 0x56, 0x55, 0xb4, 0xe0, 0x96,
	0xc9, 0x22, 0xe9, 0x97, 0x24, 0x6c, 0xe3, 0x1a, 0x25, 0xe3, 0xfc, 0x5f, 0xeb, 0xb0, 0x6d, 0x6f,
	0x2a, 0xf5, 0xab, 0xbb, 0xfe, 0x0f, 0x36, 0x64, 0x42, 0xab, 0xea, 0x51, 0x14, 0x07, 0x8c, 0x7f,
	0x09, 0x20, 0x65, 0x9a, 0x18, 0x5a, 0xcb, 0xf6, 0x23, 0x16, 0xa9, 0x44, 0x31, 0xb4, 0x96, 0x7d,
	0x4f, 0x68, 0x2c, 0xd0, 0x52, 0x32, 0x4e, 0xfb, 0xbf, 0x59, 0x91, 0xe3, 0xd9, 0x70, 0xde, 0x74,
	0x5d, 0xee, 0x60, 0x05, 0xfd, 0xf5, 0xd5, 0xe8, 0x3b, 0x15, 0xf4, 0xf9, 0xd9, 0x36, 0xfa, 0x27,
	0x05, 0xfa, 0x5a, 0x74, 0x4e, 0xf4, 0xfb, 0xe0, 0xec, 0x91, 0x94, 0xe8, 0x4a, 0x92, 0x84, 0x6d,
	0xf2, 0x7a, 0x39, 0x26, 0x45, 0xcd, 0x8b, 0x34, 0x3f, 0x5f, 0xcd, 0xcb, 0xc2, 0x50, 0x35, 0xff,
	0xd3, 0x5a, 0x51, 0xf3, 0x42, 0x70, 0x2e, 0x10, 0xfb, 0xe0, 0x0c, 0xa7, 0xd1, 0x44, 0x87, 0x52,
	0x12, 0xc2, 0xce, 0x84, 0xe1, 0xe7, 0x34, 0x35, 0xf5, 0x2e, 0x49, 0x7e, 0xad, 0x0e, 0x33, 0x26,
	0x4e, 0xc1, 0x2a, 0x8c, 0x05, 0x03, 0x0d, 0xa0, 0x13, 0xe2, 0xd3, 0x04, 0xbf, 0x1d, 0xb1, 0x88,
	0x61, 0x91, 0xf7, 0x4e, 0x68, 0xb3, 0x90, 0x0f, 0x5d, 0x49, 0x86, 0x78, 0x1a, 0xd1, 0x37, 0x6e,
	0x53, 0x6c, 0x51, 0xe2, 0xad, 0xae, 0x70, 0x1e, 0xd8, 0x3d, 0x8a, 0x23, 0x86, 0x9f, 0x25, 0x53,
	0xec, 0xb6, 0x85, 0x67, 0x16, 0xc7, 0xdf, 0x87, 0x4b, 0x0a, 0x81, 0xbd, 0x88, 0xe1, 0x09, 0xa1,
	0x09, 0xce, 0x0d, 0x8c, 0xb7, 0xca, 0x30, 0x16, 0x51, 0x57, 0xba, 0x67, 0x1a, 0xc9, 0x5d, 0xd8,
	0xd2, 0xac, 0xa3, 0x88, 0xe2, 0x6c, 0x75, 0x8f, 0xf8, 0x73, 0xbd, 0x48, 0x10, 0xbd, 0x64, 0x01,
	0x76, 0x0f, 0x5a, 0x7a, 0x1b, 0x55, 0x4a, 0x86, 0xe6, 0xae, 0xaa, 0xee, 0x22, 0x02, 0xd0, 0x08,
	0x35, 0x29, 0x56, 0xd1, 0x84, 0xd0, 0x84, 0x9d, 0xa9, 0x5c, 0x31, 0xb4, 0x09, 0xa4, 0x63, 0x05,
	0x92, 0x07, 0x26, 0x7f, 0x91, 0x50, 0x36, 0x8f, 0x52, 0x01, 0x7c, 0x2b, 0x2c, 0x18, 0x3c, 0x30,
	0xda, 0x3e, 0x1e, 0x54, 0x89, 0xba, 0xcd, 0x92, 0xa1, 0x8b, 0x13, 0x8a, 0xc7, 0x8c, 0x6b, 0x20,
	0xa9, 0x61, 0xb1, 0xf8, 0xa9, 0xc3, 0x31, 0xc9, 0x44, 0x4c, 0xda, 0xa1, 0xf8, 0x16, 0xa7, 0x8e,
	0x49, 0x76, 0x44, 0x92, 0x8c, 0x89, 0x78, 0xf0, 0x74, 0xd0, 0x0c, 0x0e, 0xda, 0x63, 0x7c, 0x8a,
	0x53, 0x17, 0x84, 0x03, 0x92, 0xb0, 0x8b, 0xa0, 0x53, 0xae, 0xdb, 0x2b, 0xd0, 0x7e, 0x94, 0x12,
	0x42, 0x47, 0x27, 0xe4, 0xad, 0xdb, 0x95, 0x3e, 0x18, 0x86, 0x9d, 0x16, 0x3d, 0x21, 0x5b, 0x91,
	0x16, 0x9b, 0xd5, 0xb4, 0x40, 0xf7, 0xa1, 0xf9, 0xdd, 0x8c, 0x25, 0x24, 0xcb, 0xdd, 0x0b, 0x22,
	0xf6, 0x57, 0x17, 0x62, 0x1f, 0x28, 0x85, 0x83, 0x8c, 0xd1, 0xb3, 0x50, 0xab, 0x5b, 0x4d, 0x69,
	0xeb, 0x9d, 0x4d, 0xe9, 0x63, 0x68, 0xed, 0x9d, 0x24, 0x69, 0x4c, 0x71, 0xe6, 0x6e, 0xaf, 0x4a,
	0x2f, 0xa3, 0xe2, 0x3d, 0x80, 0xae, 0x7d, 0x1e, 0xda, 0x82, 0xc6, 0x1b, 0x7c, 0x26, 0x72, 0xa6,
	0x1d, 0xf2, 0x4f, 0x0e, 0xdd, 0xa9, 0x7d, 0xab, 0x08, 0xe2, 0xc1, 0xda, 0xfd, 0xba, 0xff, 0xf7,
	0x1a, 0x78, 0xa3, 0xe8, 0x14, 0x57, 0x77, 0x57, 0x33, 0xd1, 0x7f, 0xd9, 0xa7, 0xb3, 0xef, 0x5f,
	0xcf, 0x33, 0x7f, 0x04, 0x97, 0x97, 0x22, 0xaf, 0x2e, 0x98, 0x3e, 0x38, 0x07, 0x94, 0x12, 0xaa,
	0xe2, 0x28, 0x09, 0x91, 0x9c, 0x4a, 0xd3, 0x84, 0xc0, 0xe2, 0xf8, 0xbf, 0xd4, 0x61, 0x47, 0x93,
	0xcf, 0x28, 0xc6, 0xd6, 0x70, 0x6b, 0x02, 0x57, 0xaf, 0x04, 0xee, 0x3a, 0xf4, 0x0e, 0x7e, 0x1c,
	0xa7, 0xf3, 0x18, 0x0f, 0x45, 0xab, 0x70, 0xd7, 0x06, 0x8d, 0xdd, 0x46, 0x58, 0x66, 0x72, 0x7b,
	0xf6, 0xf1, 0x8c, 0x9d, 0xa8, 0xf6, 0x28, 0x09, 0x79, 0x83, 0x27, 0x2c, 0x89, 0x78, 0xd8, 0xd7,
	0xe5, 0x60, 0x6c, 0x18, 0xfe, 0x4b, 0xe8, 0x97, 0x8d, 0x51, 0xbe, 0x0d, 0xca, 0x97, 0x27, 0x04,
	0x23, 0x2e, 0x7e, 0x4a, 0x62, 0xac, 0x3b, 0xde, 0x00, 0x3a, 0x6a, 0x1b, 0xcb, 0x22, 0x9b, 0xe5,
	0xff, 0xdc, 0x80, 0x96, 0x2e, 0x8a, 0x85, 0x3c, 0x7d, 0x0f, 0x4c, 0x26, 0xeb, 0x1a, 0xe5, 0xd9,
	0xed, 0x05, 0xce, 0x62, 0x42, 0x8d, 0x27, 0x86, 0xe6, 0x51, 0x14, 0xb5, 0x39, 0x94, 0xd3, 0x46,
	0x23, 0xd4, 0x24, 0xdf, 0x69, 0x8f, 0xc4, 0x58, 0x4d, 0x65, 0xe2, 0xbb, 0x68, 0x83, 0x4d, 0xbb,
	0x0d, 0x0e, 0xa0, 0xb3, 0x8f, 0xf3, 0x31, 0x4d, 0x44, 0xad, 0xaa, 0xd4, 0xb3, 0x59, 0x7c, 0x48,
	0x52, 0x8d, 0x4c, 0xa6, 0x9f, 0xa2, 0xf8, 0x7e, 0xb2, 0x05, 0xaa, 0x9b, 0x4f, 0x36, 0xbf, 0xd5,
	0x19, 0xb9, 0xab, 0xc7, 0xe8, 0xae, 0x80, 0x17, 0x05, 0x0b, 0xf3, 0x99, 0x9e, 0xa5, 0xcb, 0x77,
	0x5d, 0x6f, 0xe1, 0xae, 0xbb, 0x0a, 0xf0, 0x7c, 0x16, 0x57, 0xee, 0xc2, 0x82, 0xe3, 0x3f, 0x02,
	0xa4, 0x5f, 0x3e, 0xd9, 0x6b, 0xa2, 0x93, 0xad, 0xf4, 0x5a, 0xaa, 0x57, 0x5e, 0x4b, 0xa2, 0xf6,
	0xb2, 0xd7, 0x44, 0x0f, 0x0e, 0xfc, 0xdb, 0xc7, 0xb0, 0x63, 0xd5, 0x82, 0xc9, 0x13, 0x17, 0x9a,
	0x98, 0x52, 0x81, 0xaf, 0xdc, 0x46, 0x93, 0x1c, 0xaa, 0x03, 0x4a, 0x9f, 0xe4, 0x13, 0xb5, 0x8d,
	0xa2, 0xca, 0x47, 0x37, 0x2a, 0x47, 0xdf, 0xfd, 0xbd, 0x65, 0x9e, 0x61, 0x23, 0xf9, 0x42, 0xe4,
	0x77, 0xed, 0x21, 0x56, 0xcf, 0x9a, 0x0b, 0x41, 0xf9, 0x8d, 0xe6, 0x55, 0x1e, 0x44, 0x7e, 0x0d,
	0x7d, 0x02, 0x6d, 0xad, 0x9e, 0xa3, 0x8d, 0xe0, 0x60, 0x3a, 0x63, 0x67, 0xde, 0xa5, 0x60, 0xd5,
	0x0b, 0xcb, 0xaf, 0xa1, 0x8f, 0xa0, 0x79, 0x88, 0xd5, 0x0b, 0x22, 0x28, 0xbd, 0xed, 0xbc, 0xf2,
	0xfb, 0xc6, 0xaf, 0xa1, 0x7b, 0xd0, 0x51, 0xba, 0x62, 0x38, 0x44, 0xc1, 0xc2, 0x23, 0xcf, 0x5b,
	0x1c, 0xee, 0xfd, 0x1a, 0xba, 0x0d, 0xdb, 0xda, 0x2a, 0x11, 0xd7, 0x6f, 0xd8, 0x74, 0x89, 0x37,
	0xcd, 0x60, 0xc4, 0x68, 0x92, 0x4d, 0xfc, 0x1a, 0xba, 0x09, 0x6d, 0x8e, 0xb7, 0x7a, 0xcd, 0x95,
	0xbd, 0xf4, 0x9a, 0x41, 0x88, 0xf3, 0x79, 0xca, 0x84, 0xf1, 0x5d, 0xf9, 0x56, 0x16, 0x92, 0x57,
	0xcb, 0xf6, 0x34, 0xba, 0xd7, 0x05, 0x92, 0x72, 0x58, 0xdc, 0x08, 0x86, 0x19, 0xbb, 0xf7, 0x99,
	0x57, 0xe9, 0x70, 0xc5, 0xc9, 0x6a, 0xa6, 0x2c, 0x8b, 0xed, 0xdd, 0x44, 0xb5, 0xf0, 0x93, 0xcb,
	0x1b, 0x5a, 0x1a, 0x32, 0x14, 0xaa, 0x65, 0x2e, 0x84, 0x62, 0x61, 0xf0, 0xf5, 0x6b, 0xe8, 0x73,
	0xe8, 0x1d, 0x62, 0x6b, 0x98, 0x33, 0xab, 0xbc, 0x60, 0xe5, 0xa0, 0x27, 0x40, 0xe8, 0x14, 0xcb,
	0xce, 0x8c, 0x29, 0x8b, 0x3d, 0xd9, 0xaf, 0xa1, 0x6b, 0xb0, 0x29, 0xcd, 0x5e, 0x50, 0xb7, 0x2c,
	0xff, 0x16, 0xba, 0x1c, 0x03, 0xa3, 0x72, 0x39, 0x58, 0xdd, 0x82, 0xbd, 0x2b, 0xc1, 0x3b, 0xba,
	0x84, 0x5f, 0x43, 0xfb, 0xb0, 0x63, 0x59, 0xa7, 0xef, 0x51, 0xd4, 0x0f, 0x96, 0xb4, 0x01, 0xef,
	0x62, 0xb0, 0xec, 0x3e, 0xf6, 0x6b, 0xe8, 0x4b, 0xe9, 0xa3, 0x1a, 0x29, 0xd0, 0x76, 0x50, 0x9d,
	0x59, 0xdf, 0x83, 0xd1, 0x0d, 0x80, 0x43, 0xcc, 0xf4, 0x75, 0x0c, 0x81, 0xa9, 0x39, 0xaf, 0x6d,
	0x60, 0x12, 0x31, 0xeb, 0x58, 0xde, 0xa0, 0x42, 0xe6, 0xf5, 0x83, 0x25, 0x17, 0x80, 0x5f, 0x43,
	0x77, 0xa0, 0x57, 0xfa, 0xb7, 0x06, 0x5d, 0x0c, 0x96, 0xfd, 0x7b, 0x63, 0xc3, 0x7b, 0x07, 0x2e,
	0x58, 0x7b, 0xf1, 0xfb, 0x05, 0xed, 0x04, 0x8b, 0xd7, 0x94, 0xb5, 0xe4, 0xe1, 0xff, 0x61, 0x67,
	0x4c, 0xa6, 0xc1, 0x24, 0x61, 0x27, 0xf3, 0xe3, 0x60, 0x42, 0xee, 0x92, 0x80, 0xce, 0xc6, 0x2f,
	0x5b, 0xc1, 0xed, 0x2f, 0xc4, 0x9f, 0x46, 0xc7, 0x1b, 0xe2, 0xe7, 0xd3, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xa6, 0x7f, 0x5d, 0x28, 0x62, 0x12, 0x00, 0x00,
}
