// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: message/shipment_dto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 覆盖区域
type SCoverageValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Lng     float64 `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng"`
	Lat     float64 `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat"`
	Radius  int32   `protobuf:"varint,5,opt,name=radius,proto3" json:"radius"`
	Address string  `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	AreaId  int64   `protobuf:"varint,7,opt,name=areaId,proto3" json:"areaId"`
}

func (x *SCoverageValue) Reset() {
	*x = SCoverageValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCoverageValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCoverageValue) ProtoMessage() {}

func (x *SCoverageValue) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCoverageValue.ProtoReflect.Descriptor instead.
func (*SCoverageValue) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{0}
}

func (x *SCoverageValue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SCoverageValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SCoverageValue) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *SCoverageValue) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SCoverageValue) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *SCoverageValue) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SCoverageValue) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

type ShipmentOrderListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*SShipmentOrder `protobuf:"bytes,1,rep,name=value,proto3" json:"value"`
}

func (x *ShipmentOrderListResponse) Reset() {
	*x = ShipmentOrderListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipmentOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentOrderListResponse) ProtoMessage() {}

func (x *ShipmentOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentOrderListResponse.ProtoReflect.Descriptor instead.
func (*ShipmentOrderListResponse) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ShipmentOrderListResponse) GetValue() []*SShipmentOrder {
	if x != nil {
		return x.Value
	}
	return nil
}

// 发货单
type SShipmentOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编号
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 订单编号
	OrderId int64 `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId"`
	// 子订单编号
	SubOrderId int64 `protobuf:"varint,3,opt,name=subOrderId,proto3" json:"subOrderId"`
	// 快递SP编号
	ExpressSpId int64 `protobuf:"varint,4,opt,name=expressSpId,proto3" json:"expressSpId"`
	// 快递SP单号
	ShipOrderNo string `protobuf:"bytes,5,opt,name=shipOrderNo,proto3" json:"shipOrderNo"`
	// 物流日志
	ShipmentLog string `protobuf:"bytes,6,opt,name=shipmentLog,proto3" json:"shipmentLog"`
	// 运费
	Amount float64 `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount"`
	// 实际运费
	FinalAmount float64 `protobuf:"fixed64,8,opt,name=finalAmount,proto3" json:"finalAmount"`
	// 发货时间
	ShipTime int64 `protobuf:"varint,9,opt,name=shipTime,proto3" json:"shipTime"`
	// 状态
	State int32 `protobuf:"varint,10,opt,name=state,proto3" json:"state"`
	// 更新时间
	UpdateTime int64 `protobuf:"varint,11,opt,name=updateTime,proto3" json:"updateTime"`
	// 配送项目
	Items []*SShipmentItem `protobuf:"bytes,12,rep,name=items,proto3" json:"items"`
}

func (x *SShipmentOrder) Reset() {
	*x = SShipmentOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SShipmentOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SShipmentOrder) ProtoMessage() {}

func (x *SShipmentOrder) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SShipmentOrder.ProtoReflect.Descriptor instead.
func (*SShipmentOrder) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{2}
}

func (x *SShipmentOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SShipmentOrder) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *SShipmentOrder) GetSubOrderId() int64 {
	if x != nil {
		return x.SubOrderId
	}
	return 0
}

func (x *SShipmentOrder) GetExpressSpId() int64 {
	if x != nil {
		return x.ExpressSpId
	}
	return 0
}

func (x *SShipmentOrder) GetShipOrderNo() string {
	if x != nil {
		return x.ShipOrderNo
	}
	return ""
}

func (x *SShipmentOrder) GetShipmentLog() string {
	if x != nil {
		return x.ShipmentLog
	}
	return ""
}

func (x *SShipmentOrder) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SShipmentOrder) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *SShipmentOrder) GetShipTime() int64 {
	if x != nil {
		return x.ShipTime
	}
	return 0
}

func (x *SShipmentOrder) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *SShipmentOrder) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *SShipmentOrder) GetItems() []*SShipmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 发货单详情
type SShipmentItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编号
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// 商品交易快照编号
	SnapshotId int64 `protobuf:"varint,2,opt,name=snapshotId,proto3" json:"snapshotId"`
	// 商品数量
	Quantity int32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity"`
	// 运费
	Amount float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount"`
	// 实际运费
	FinalAmount float64 `protobuf:"fixed64,5,opt,name=finalAmount,proto3" json:"finalAmount"`
}

func (x *SShipmentItem) Reset() {
	*x = SShipmentItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SShipmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SShipmentItem) ProtoMessage() {}

func (x *SShipmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SShipmentItem.ProtoReflect.Descriptor instead.
func (*SShipmentItem) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{3}
}

func (x *SShipmentItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SShipmentItem) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *SShipmentItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SShipmentItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SShipmentItem) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

type LogisticFlowTrackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipperCode  string `protobuf:"bytes,1,opt,name=shipperCode,proto3" json:"shipperCode"`
	LogisticCode string `protobuf:"bytes,2,opt,name=logisticCode,proto3" json:"logisticCode"`
	Invert       bool   `protobuf:"varint,3,opt,name=invert,proto3" json:"invert"`
}

func (x *LogisticFlowTrackRequest) Reset() {
	*x = LogisticFlowTrackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogisticFlowTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogisticFlowTrackRequest) ProtoMessage() {}

func (x *LogisticFlowTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogisticFlowTrackRequest.ProtoReflect.Descriptor instead.
func (*LogisticFlowTrackRequest) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{4}
}

func (x *LogisticFlowTrackRequest) GetShipperCode() string {
	if x != nil {
		return x.ShipperCode
	}
	return ""
}

func (x *LogisticFlowTrackRequest) GetLogisticCode() string {
	if x != nil {
		return x.LogisticCode
	}
	return ""
}

func (x *LogisticFlowTrackRequest) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

type OrderLogisticTrackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipOrderId int64 `protobuf:"zigzag64,1,opt,name=shipOrderId,proto3" json:"shipOrderId"`
	Invert      bool  `protobuf:"varint,2,opt,name=invert,proto3" json:"invert"`
}

func (x *OrderLogisticTrackRequest) Reset() {
	*x = OrderLogisticTrackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderLogisticTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLogisticTrackRequest) ProtoMessage() {}

func (x *OrderLogisticTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLogisticTrackRequest.ProtoReflect.Descriptor instead.
func (*OrderLogisticTrackRequest) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{5}
}

func (x *OrderLogisticTrackRequest) GetShipOrderId() int64 {
	if x != nil {
		return x.ShipOrderId
	}
	return 0
}

func (x *OrderLogisticTrackRequest) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

// 发货单追踪
type SShipOrderTrack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 返回状态码
	Code int32 `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code"`
	// 返回错误信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	// 物流单号
	LogisticCode string `protobuf:"bytes,3,opt,name=logisticCode,proto3" json:"logisticCode"`
	// 承运商代码
	ShipperCode string `protobuf:"bytes,4,opt,name=shipperCode,proto3" json:"shipperCode"`
	// * 承运商名称
	ShipperName string `protobuf:"bytes,5,opt,name=shipperName,proto3" json:"shipperName"`
	// 发货状态
	ShipState string `protobuf:"bytes,6,opt,name=shipState,proto3" json:"shipState"`
	// 更新时间
	UpdateTime int64 `protobuf:"zigzag64,7,opt,name=updateTime,proto3" json:"updateTime"`
	// 包含发货单流
	Flows []*SShipFlow `protobuf:"bytes,8,rep,name=flows,proto3" json:"flows"`
}

func (x *SShipOrderTrack) Reset() {
	*x = SShipOrderTrack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SShipOrderTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SShipOrderTrack) ProtoMessage() {}

func (x *SShipOrderTrack) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SShipOrderTrack.ProtoReflect.Descriptor instead.
func (*SShipOrderTrack) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{6}
}

func (x *SShipOrderTrack) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SShipOrderTrack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SShipOrderTrack) GetLogisticCode() string {
	if x != nil {
		return x.LogisticCode
	}
	return ""
}

func (x *SShipOrderTrack) GetShipperCode() string {
	if x != nil {
		return x.ShipperCode
	}
	return ""
}

func (x *SShipOrderTrack) GetShipperName() string {
	if x != nil {
		return x.ShipperName
	}
	return ""
}

func (x *SShipOrderTrack) GetShipState() string {
	if x != nil {
		return x.ShipState
	}
	return ""
}

func (x *SShipOrderTrack) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *SShipOrderTrack) GetFlows() []*SShipFlow {
	if x != nil {
		return x.Flows
	}
	return nil
}

// 发货流
type SShipFlow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 记录标题
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject"`
	// 记录时间
	CreateTime string `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime"`
	// 备注
	Remark string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark"`
}

func (x *SShipFlow) Reset() {
	*x = SShipFlow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_shipment_dto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SShipFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SShipFlow) ProtoMessage() {}

func (x *SShipFlow) ProtoReflect() protoreflect.Message {
	mi := &file_message_shipment_dto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SShipFlow.ProtoReflect.Descriptor instead.
func (*SShipFlow) Descriptor() ([]byte, []int) {
	return file_message_shipment_dto_proto_rawDescGZIP(), []int{7}
}

func (x *SShipFlow) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SShipFlow) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SShipFlow) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_message_shipment_dto_proto protoreflect.FileDescriptor

var file_message_shipment_dto_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a,
	0x0e, 0x53, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x65,
	0x61, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49,
	0x64, 0x22, 0x42, 0x0a, 0x19, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x53, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xf2, 0x02, 0x0a, 0x0e, 0x53, 0x53, 0x68, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x53, 0x70, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x53, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x0c, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x53,
	0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x78, 0x0a, 0x18, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x46, 0x6c,
	0x6f, 0x77, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x22, 0x55, 0x0a, 0x19,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x69,
	0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x0b,
	0x73, 0x68, 0x69, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x6e, 0x76, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x22, 0x87, 0x02, 0x0a, 0x0f, 0x53, 0x53, 0x68, 0x69, 0x70, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x69,
	0x70, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x12, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x53, 0x68,
	0x69, 0x70, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x22, 0x5d, 0x0a,
	0x09, 0x53, 0x53, 0x68, 0x69, 0x70, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x42, 0x1f, 0x0a, 0x13,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x67, 0x6f, 0x32, 0x6f, 0x2e,
	0x72, 0x70, 0x63, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_shipment_dto_proto_rawDescOnce sync.Once
	file_message_shipment_dto_proto_rawDescData = file_message_shipment_dto_proto_rawDesc
)

func file_message_shipment_dto_proto_rawDescGZIP() []byte {
	file_message_shipment_dto_proto_rawDescOnce.Do(func() {
		file_message_shipment_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_shipment_dto_proto_rawDescData)
	})
	return file_message_shipment_dto_proto_rawDescData
}

var file_message_shipment_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_message_shipment_dto_proto_goTypes = []interface{}{
	(*SCoverageValue)(nil),            // 0: SCoverageValue
	(*ShipmentOrderListResponse)(nil), // 1: ShipmentOrderListResponse
	(*SShipmentOrder)(nil),            // 2: SShipmentOrder
	(*SShipmentItem)(nil),             // 3: SShipmentItem
	(*LogisticFlowTrackRequest)(nil),  // 4: LogisticFlowTrackRequest
	(*OrderLogisticTrackRequest)(nil), // 5: OrderLogisticTrackRequest
	(*SShipOrderTrack)(nil),           // 6: SShipOrderTrack
	(*SShipFlow)(nil),                 // 7: SShipFlow
}
var file_message_shipment_dto_proto_depIdxs = []int32{
	2, // 0: ShipmentOrderListResponse.value:type_name -> SShipmentOrder
	3, // 1: SShipmentOrder.items:type_name -> SShipmentItem
	7, // 2: SShipOrderTrack.flows:type_name -> SShipFlow
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_shipment_dto_proto_init() }
func file_message_shipment_dto_proto_init() {
	if File_message_shipment_dto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_shipment_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCoverageValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_shipment_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipmentOrderListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_shipment_dto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SShipmentOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_shipment_dto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SShipmentItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_shipment_dto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogisticFlowTrackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_shipment_dto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderLogisticTrackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_shipment_dto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SShipOrderTrack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_shipment_dto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SShipFlow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_shipment_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_shipment_dto_proto_goTypes,
		DependencyIndexes: file_message_shipment_dto_proto_depIdxs,
		MessageInfos:      file_message_shipment_dto_proto_msgTypes,
	}.Build()
	File_message_shipment_dto_proto = out.File
	file_message_shipment_dto_proto_rawDesc = nil
	file_message_shipment_dto_proto_goTypes = nil
	file_message_shipment_dto_proto_depIdxs = nil
}
