/**
 * This file is auto generated by tto v0.4.5 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2021 <no value>, All rights reserved.
 *
 * name : comm_qr_template_dao.go
 * author : jarrysix
 * date : 2021/12/02 10:37:45
 * description :
 * history :
 */
package dao





import(
    "go2o/core/dao/model"
)

type ICommQrTemplateDao interface{
    // Get CommQrTemplate
    GetQrTemplate(primary interface{})*model.CommQrTemplate
    // GetBy CommQrTemplate
    GetQrTemplateBy(where string,v ...interface{})*model.CommQrTemplate
    // Count CommQrTemplate by condition
    CountQrTemplate(where string,v ...interface{})(int,error)
    // Select CommQrTemplate
    SelectQrTemplate(where string,v ...interface{})[]*model.CommQrTemplate
    // Save CommQrTemplate
    SaveQrTemplate(v *model.CommQrTemplate)(int,error)
    // Delete CommQrTemplate
    DeleteQrTemplate(primary interface{}) error
    // Batch Delete CommQrTemplate
    BatchDeleteQrTemplate(where string,v ...interface{})(int64,error)
    // Query paging data
    PagingQueryQrTemplate(begin, end int, where, orderBy string) (total int, rows []map[string]interface{})
}